import type { School, ChoiceItem, Classmate, CustomClassmateOption } from '../types';

export const SCHOOLS_DATA: { [key: string]: School } = {
  halidew: { id: 'kaliam_tech', title: 'KALIAM TECH', description: "The forefront of magitechnological innovation the world over, almost every modern luxury we take for granted has its roots in Kaliam researchers. Hard-working and ambitious students will fit in well, but idler sorts may be put off by the often brutal workload. You'll be the surrounded by brilliant minds.", costBlurb: "Juathas Sigil: Refunds 2 Blessing Points for Blessings administered by Marga.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch1.jpg' },
  shinar: { id: 'sheol_ academy', title: 'SHEOL ACADEMY', description: "The oldest school of magecraft, Sheol seems strange and impenetrable to new students, but if you apply yourself enough (or have good connections), you can slowly work your way into its ancient, exclusive sororities and discover there's a lot more going on here than meets the eye. There's long-buried secrets hidden around every corner, if you know where to look.", costBlurb: "Sinthru Sigil: Refunds 2 Blessing Points.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch2.jpeg' },
  unterseeisch: { id: 'st_lucindas', title: "ST. LUCINDA'S SCHOOL", description: "A small town in itself, St. Lucinda's is probably the most laid-back and fun school out there, with quite relaxed standards and lots of partying. While students here are often stereotyped as lazy, there's actually plenty of opportunities for more ambitious student to learn a lot from the school's wise Sea Saints.", costBlurb: "Juathas Sigil: Refunds 2 Blessing Points for Blessings administered by Fidelia.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch3.jpg' },
  valsereth: { id: 'strasmara', title: 'STRASMARA', description: "This Earth's equivalent of the Ivy League. This school boasts some of the smartest and most powerful mages in the world, but its students are stereotyped as snobbish and egotistical. It's the forefront of efforts to research ways to push the Blessings to their limits, and is even the institution that hosts the Irin Gauntlet. Can be stressful due to its high standards.", costBlurb: "Xuth Sigil: Refunds 3 Blessing Points.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch4.png' },
  gohwood: { id: 'eglaesaria', title: 'THE EGLAESARIA', description: "Formed by a group of powerful dragons many millennia ago, only one of these dragons still lives, serving as the academy's massive, imposing headmaster. It prizes a more stoic, combat-centered approach to magic, and many of the greatest warriors in history were taught here. Honor is paramount.", costBlurb: "Juathas Sigil: Refunds 2 Blessing Points for Blessings administered by Arabella.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch5.jpg' },
  palisade: { id: 'triumph_towers', title: 'TRIUMPH TOWERS', description: "Tied for the tallest towers in New Palisade, so much so that they use portals instead of elevators. This is a private school known as the spot for rich kids, and life here is pretty cushy and opulent and lavish, although it can sometimes feel unnervingly corporate. If influence is treasured here, so it's a good choice for those who want to establish some celebrity status.", costBlurb: "Lekolu Sigil: Refunds 2 Blessing Points.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch6.jpg' },
  rovines: { id: 'droudnore', title: 'DROUDNORE INSTITUTE', description: "Perhaps the most modest school, the Droudnore Institute is known for its smokestacks, situated on its own spacious private island. Criticized by some for having a laxer curriculum compared to other schools, but it's a perfect choice for aspiring mages who want to learn very practical magic, and don't want to fret about with theoretical magic like at the Strasmara.", costBlurb: "Juathas Sigil: Refunds 1 Blessing Point.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch7.jpg' },
  jipangu: { id: 'horikoshi_koko', title: 'HORIKOSHI KOKO', description: "Placed atop Mount Shikawa, just above the clouds, a variety of charms and hexes make it impossible for all mundanes to ever access. Students tend to get there via portals built in their various shrines. It is steeped in ancient tradition, and constantly alive with fun festivals, parades, ceremonies, and other activities.", costBlurb: "Juathas Sigil: Refunds 1 Blessing Point for Blessings administered by Dryasdoa.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/sch8.jpg' },
};

export const HEADMASTERS_DATA: ChoiceItem[] = [
    { id: 'waning', title: 'WANING', cost: 'Grants +2 FP', description: "They were a legend centuries ago, but over time, their competence has only dwindled. Now, the school is chronically unorganized and mismanaged, with them only kept due to their influence and long tenure.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/head1.png' },
    { id: 'stringent', title: 'STRINGENT', cost: 'Grants +1 FP', description: "They hail from the old-fashioned 'spare the rod, spoil the child' ideas of schooling. They're just as competent, if not more so, but their sternness and their short temper means you definitely don't want to earn their ire.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/head2.png' },
    { id: 'competent', title: 'COMPETENT', cost: 'Costs 0 FP', description: "They're youthful in how laid-back and friendly they are, but show their age in their great wisdom and ability to manage the busy school with ease. They tend to work in the background, rarely taking an active role.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/head3.png' },
    { id: 'sagely', title: 'SAGELY', cost: 'Costs -2 FP', description: "With centuries of knowledge and experience, your education will be cultivated to a razor point under their management. They overflow with wisdom, and you'll look forward to your rare conversations with them.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/head4.png' },
    { id: 'venerable', title: 'VENERABLE', cost: 'Costs -4 FP', description: "A legendary scholar revered around the world, you are almost awed at their brilliance. Despite their prestige, they make a point to dedicate time to personally assisting and bonding with students.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/head5.png' },
];

export const TEACHERS_DATA: ChoiceItem[] = [
    { id: 'mama_bear', title: 'THE MAMA BEAR', cost: 'Costs -1 FP', description: "Eminently motherly and protective, she seemingly has infinite free time to devote to personally bonding with each student, not only educating them but offering support and help with all of their problems.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher1.png' },
    { id: 'entertainer', title: 'THE ENTERTAINER', cost: 'Costs -1 FP', description: "Their classes feel less like lectures and more like uproarious comedy bits, yet you still learn a ton! Their teaching methods are brilliant and engaging, and they'll make sure you get through class stress-free.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher2.png' },
    { id: 'sweetheart', title: 'THE SWEETHEART', cost: 'Costs -1 FP', description: "A walking bundle of pure wholesomeness, bringing fresh-baked cookies to class and acting like a mom more than a teacher. The problem is, they're so coddling it can feel like you aren't learning as much...", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher3.png' },
    { id: 'professional', title: 'THE PROFESSIONAL', cost: 'Costs 0 FP', description: "They're not your friend, they're your teacher. They will be strict, but fair, and if you're willing to put in the effort, you'll find you learned more in their class than any others. Just don't expect any coddling.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher4.png' },
    { id: 'geek', title: 'THE GEEK', cost: 'Costs 0 FP', description: "They're super passionate about their chosen field, and their class is highly organized and optimized. However, they can sometimes have trouble expressing their knowledge, and may move too fast.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher5.png' },
    { id: 'free_spirit', title: 'FREE SPIRIT', cost: 'Costs 0 FP', description: "Super kind, almost overly so, and a bit disorganized and fast-and-loose with their teachings. Oft experiments with teaching techniques, which sometimes work extremely well, and sometimes go terribly.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher6.png' },
    { id: 'oddity', title: 'THE ODDITY', cost: 'Costs 0 FP', description: "Your teacher actually isn't human, but a fascinating or mystical creature of some sort! Sure, this will result in rather questionable effectiveness at teaching... but in my opinion, the awe and novelty are worth it.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher7.png' },
    { id: 'inexperienced', title: 'THE INEXPERIENCED', cost: 'Grants +1 FP', description: "They're trying their best, but they're obviously brand new at this. They're often shy and nervous in front of class, and tend to be pretty clumsy and unorganized. Maybe they'll get better, with a little help?", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher8.png' },
    { id: 'sleeper', title: 'THE SLEEPER', cost: 'Grants +1 FP', description: "They're likeable, at least... but they're just so tired all the time. Nobody knows why, but it seriously affects their teaching. Oft they'll just have you study amongst yourselves while they nap at their desk.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher9.png' },
    { id: 'curmudgeon', title: 'THE CURMUDGEON', cost: 'Grants +2 FP', description: "They've got a nasty temper and zero tolerance for any impropriety, slacking or disobedience. They're just fine if you don't do anything wrong, but the atmosphere in their class is tense to say the least. Everyone is afraid of them!", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/teacher10.png' },
];

export const DURATION_DATA: ChoiceItem[] = [
    { id: '2_years', title: '-2 YEARS', cost: 'Grants +30 FP, Grants +15 BP', description: "You want to get out the door as quick as possible so you can start getting some hands-on experience! You'll be missing out on a lot of educational opportunities, though.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/year1.png' },
    { id: '6_years', title: '-6 YEARS', cost: 'Costs +0 FP', description: "The most common length of time by far. This is enough to get students a decent education in whatever will ensure their success in future careers. Considered the goldilocks zone.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/year2.png' },
    { id: '10_years', title: '-10 YEARS', cost: 'Grants +20 BP', description: "A more uncommon choice fit for more studious mages. You will gain more appreciation for your Blessings, though your lack of job experience may be a boon for your competition.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/year3.png' },
    { id: '15_years', title: '-15 YEARS', cost: 'Grants +35 BP', description: "By now, you've been here for a majority of your life. It's second home to you now, but you'll have to say painful goodbyes to the many friends who move on before you.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/year4.png' },
    { id: '20_years', title: '+20 YEARS', cost: 'Grants +50 BP', description: "You have virtually been lost in the sauce of science! You'll learn much, but you'll have to wonder whether your time would've been better spent gaining practical experience out in the field.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/year5.png' },
];

export const CLUBS_DATA: ChoiceItem[] = [
    { id: 'combat', title: 'JOIN THE COMBAT D\'ÉQUIPE TEAM', cost: 'Costs -6 FP', description: "Join a team of fighters and battle other teams in the coliseums to ascend through the brackets and win dazzling tournaments! Said coliseums are placed in pocket dimensions that ensure that no fatal or permanent injuries can be suffered by any participants. Almost everything goes except Sinthru magic.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club1.png' },
    { id: 'racer', title: 'BECOME A SEGALANYA RACER', cost: 'Costs -4 FP', description: "Settle disputes on whose method of traveling is fastest, in races that can span from only a mile or so, all the way up to circumnavigating the entire planet! Pretty much anything goes, from flying on a broomstick to soaring on a jet plane. The only rules no interfering with other racers, and no teleportation.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club2.png' },
    { id: 'mazball', title: 'JOIN THE MAZBALL TEAM', cost: 'Costs -4 FP', description: "Kind of like basketball, but imagine it with the 'nets' a half a mile apart, and both teams can fly, move fast enough to break the sound barrier, and sabotage eachother with a dizzying variety of spells. Needless to say, Mazball matches are incredibly hard to follow, but entertaining to watch nonetheless.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club3.png' },
    { id: 'student_council', title: 'STUDENT COUNCIL', cost: 'Costs -3 FP', description: "Student council president is basically the highest level of power you can have over your peers (short of becoming faculty). Competition is fierce, though! It's good practice if considering a political career.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club4.png' },
    { id: 'study_hall', title: 'STUDY HALL', cost: 'Costs -1 FP', description: "Let's be honest, 'Study hall' is pretty much just a pretense for the geeky girls to get together and do what they normally do, but with more people, and some snacks. At least you can be sure there won't be those weird cartoons they make over in Jipangu.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club5.png' },
    { id: 'community_watch', title: 'COMMUNITY WATCH', cost: 'Costs -1 FP', description: "Technically, they're only supposed to be doing stuff like rescuing cats from trees. Off the record, they go out and stop bank robberies and such! They're big on heroics... even if it doesn't always go well.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club6.png' },
    { id: 'school_band', title: 'SCHOOL BAND', cost: 'Costs -2 FP', description: "I cannot express in words what magic instruments sound like. Just know it's the kind of sound that moves your very soul. Good way to get fame, too, given they perform for all sorts of major venues.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club7.png' },
    { id: 'art_club', title: 'ART CLUB(S)', cost: 'Costs -1 FP', description: "Poetry, painting, knitting... whatever kind of art you're into, I'm sure there's a club out there. See cool art and show off your own works! Creating art is nourishing to the soul, or so I've always heard.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club8.png' },
    { id: 'beastmastery', title: 'BEASTMASTERY CLUB', cost: 'Costs -3 FP', description: "Made for students planning to own a familiar, this club's members meet and learn how to train and interact with a wide variety of fantastical creatures. If you like getting animals, this is the best club ever.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club9.png' },
    { id: 'outdoorsmanship', title: 'OUTDOORSMANSHIP CLUB', cost: 'Costs -3 FP', description: "A small but extremely friendly bunch of mages who like exploring the far reaches of the world, going on sight-seeing tours through Dominions before stopping to set up cozy little camps in the wilds.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club10.png' },
    { id: 'fitness_club', title: 'FITNESS CLUB', cost: 'Costs -3 FP', description: "Reaching your potential isn't just about learning! It also requires dedicated practice and training. This club offers endless encouragement and support, helping you to your goals free of judgement.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club11.png' },
    { id: 'theatre_club', title: 'THEATRE CLUB', cost: 'Costs -3 FP', description: "Express yourself by writing, dancing, or performing in plays, alongside a super creative and laid-back bunch! This will hone a bunch of skills, with acting teaching you to manipulate and persuade people.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club12.png' },
    { id: 'school_nurse', title: 'SCHOOL NURSE', cost: 'Costs -3 FP', description: "The hardest-working bunch around, helping their peers through injuries, Blessings of reinforcement, counselling, physical training, and etc. Great if you want to learn to be a healer or otherwise support.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club13.png' },
    { id: 'night_school', title: 'NIGHT SCHOOL', cost: 'Costs -2 FP', description: "Vampires and werewolves and... scaries of all -- oops! The girls that attend night school tend to be quite spooky, but they're nicer than they look. All being outcasts, they stick together like glue.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club14.png' },
    { id: 'sukeban_gang', title: 'SUKEBAN GANG', cost: 'Costs -3 FP', description: "A band of juvenile delinquents rebelling against social norms and generally getting into trouble. They're loyal to each other like a family through thick and thin -- there's no other group as close-knit.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/club15.png' },
];

export const MISC_ACTIVITIES_DATA: ChoiceItem[] = [
    { id: 'mentor', title: 'MENTOR', cost: 'Cost: Varies, Grants varies', description: "Very lucky and promising mages sometimes get assigned a mentor! These are skilled and experienced mages who will manage your education. Choose a Colleague from page 6, or create your own, although their FP price is doubled. However, you gain FP equal to half of the amount of FP you had to spend.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/mis1.png' },
    { id: 'puppy_love', title: 'PUPPY LOVE', cost: 'Costs -1 FP', description: "And they called it puppy loooove... Choose from your Classmates. What starts as an schoolyard crush can blossom into a relationship that lasts you centuries! You can always try romance, but this option guarantees it will work. How quickly, though, depends on the effort you put in.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/mis2.png' },
    { id: 'teachers_assistant', title: 'TEACHERS ASSISTANT', cost: 'Costs -5 FP, Grants +8 BP', description: "Requires >10 Years or greater. They say the best way to internalize something is to teach it to somebody else. For this reason, as you reach a high level in your discipline, it is a great idea to help a teacher instruct a class! You won't usually be lecturing, but you will be helping the students learn.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/mis3.png' },
    { id: 'adjunct_professor', title: 'ADJUNCT PROFESSOR', cost: 'Costs -8 FP, Grants +14 BP', description: "Requires >15 Years or greater, and Teachers Assistant. You're basically faculty now! Well, not really. But you're still participating in academic research at the institution, and you're even teaching your very own classes! This is the perfect opportunity to teach and inspire a whole generation of mages.", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/mis4.png' },
];

export const CLASSMATES_DATA: Classmate[] = [
    { id: 'keeling', name: 'KEELING', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Subatomic', otherPowers: 'Far-field, Psychic, Force II', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c1.png', description: "What a strange mage she is, with a lower body looking like some sort of giant, sand-blanched serpent. She's quite powerful, if she stares at a mundane with enough concentration, she can make it turn into a pile of sand, or cause storms of sand powerful enough to circumvent and wound mages. She's thus been set as the guardian of the Labyrinth of Concordia, which contains the sum of the world's knowledge, buried in the annuls of the college. Quite lazy, she naps most of the day away -- preferably coiled up tight around somebody, considering people warm and comfy. Hope you don't mind a few tons of snake lady in your bed. If she chooses you to be her 'space,' she can become quite loyal and affectionate, in her own way. She loves to read, and remembers an impossible amount of trivia. When angered enough, she goes from cute to properly terrifying!" },
    { id: 'starla', name: 'STARLA', cost: 'Costs -1 FP', birthplace: 'Halidew Station', signature: 'Subatomic', otherPowers: 'Sustaining Bond, Healing Bits, Guardian Angel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c2.png', description: "The justice system usually balks at capital punishment, preferring rehabilitation, but not even the Mother could coax the vileness from the archfiend Ebrex. She was instead forced to remain 'dead,' ending the Sinthru threat. Starla still needs her old self's borders, in occasional nightmares, and she's still burdened by the lingering guilt. She's trying to spend this new existence ignoring lives instead of taking them. She's currently the curator at the city's museum, believing those who do not remember the past are doomed to repeat it. Very prim and proper, she isolates herself and finds social situations to be quite perturbed by crudeness. Bright and passionate, she likes sharing her love of learning with others, and will help immensely with passing your classes and training with new spells. Commonly called an old soul, and loves music from centuries ago. She'll be super proud and excited to show you her museum collection." },
    { id: 'nyla', name: 'NYLA', cost: 'Costs -3 FP', birthplace: 'Halidew Station', signature: 'Subatomic', otherPowers: 'Teleportation, A-Space, Camouflage, All-Seeing, Arcane Matter, Smarts + Material Transmutation', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c3.png', description: "Hmm... a tragic case. In Halidew, it is a rite of passage at primary school graduation to create and release an automaton known as a steambot. Nyla and her friend, Lexie, thought they could perfectly recreate the dreaded Exterminator-bot, but it exploded. Lexie was killed in the explosion, and a grieving Nyla was left with a malfunctioned horribly, and she was left with a robotic curse. She was much more popular than Nyla ever was, so from then on, fair or not, people branded Nyla the girl whose incompetence cost the city a very beloved mage. She's been a recluse ever since, tinkering with her robots and avoiding everyone else. She is used to be a whiz! a jokester and really clever besides. She'll even be a friend to you if you get past her defenses. She's been known to throw parties and performances to entertain everyone in town, skipping around with a goofy smile on her face. If you could get the old her back, you'd have a great friend." },
    { id: 'araminta', name: 'ARAMINTA', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Summon Creature', otherPowers: 'Lesser Summon, Common Ground, Pact Magic, Summon Weather, Natural Environment, Shifting Weather, Artificial Environment, Broken Space, Broken Time', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c4.png', description: "She's not trying to get you to join a cult, is she? We're not 'Xarkaz the Forgotten One's' kids. I don't care who 'Xarkaz the Forgotten One' is. I swear, those hermit ecdesiast families on the outskirts of Shinar believe in the damndest things. Lovely girl otherwise, though. And to be fair, I suspect the reason she gets into those things is partly to help support her poor, beloved grandmother. After the death of her mother, who was, at those millennia ago, a member of the same... On that note, she has a verse of her own. And it can't be a friendly place, judging by the horrid tentacle creatures with a thousand eyes she can bring howling out of it. But if you're brave enough, feel free to take her up on her offer to join her in her 'pot of tea.' It's probably just a front, but, then again, I think she's a sweet girl who desperately wants to be understood. Talking to her, sometimes you do get the feeling she might be onto something..." },
    { id: 'orenda', name: 'ORENDA', cost: 'Costs -2 FP', birthplace: 'Shinar', signature: 'Undead', otherPowers: 'Dark Grasping Hands, Raise from your Graves, Spirit Medium, Fata Morgana Curse', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c5.png', description: "She really wants to be a good mage! She's trying her best! But her anxiety gets the better of her, and she often clumsily whiffs her attempts at magic in the most embarrassing ways. At least her wise undead guardian-turned-father figure, Xerxes, is always there to pick her up when she's down. Still, she'd prefer to see her daughter succeed on her own. She's the last in a line of the best necromancers in history, hoping to make her proud one day. I think the poor girl is still in denial over the fact her mother doesn't care about her in the slightest... Beyond that, though, she's fun to hang out with. Geeky, quirky, and gets all probably excited when allowed to gush about all of her favorite myths and legends in extreme detail. She'll know the lore of every treasure or ruin you find out on your adventures -- provided you can convince her overprotective guardian to let her go out." },
    { id: 'thalia', name: 'THALIA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Superhuman', otherPowers: 'Hypnosis, Psychic, Vampire, Psychic Force I, Strength +, Speed +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c6.png', description: "Born into the mysterious Nokomis family, a bloodline through which vampirism runs due to an age-old curse. You get the sense she's been bullied for her vampiric nature, which may be why she became a bit of a bully herself as a way of getting back at the world. She seems to enjoy that role at times. Still, you could get her to be a friend of yours. You still get hints that she likes you more than she lets on. She seems to subvert them with jealousy because she's convinced they'd expect too much. She seems to be worried that she'd want them to be too much, or something like that, which I can understand. To be kind to her, rather than judgmental, can make her shy condescension give way to shocked, flustered stammering. Maybe there's a way to break through to her softer side?" },
    { id: 'valorie', name: 'VALORIE', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Signature', otherPowers: 'Psychic Force I, Forcefield, Sonic Boom, Plasma Shells, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c7.png', description: "Runs for someone boastful to be able to back up their boasts, but she does so in a style so grand she sways the younger mage population -- making her the 'Mayqueen' this millennium to solo a Grimsvaper-tier Aetimili! She's quite prideful and playfully braggadocious, but not in the all-too-common way that drags other people down. Instead, she strives to build her friends up, and is the first to sing their praises if they match or surpass her achievements. Her self-confidence can waiver, and compliments often fall on deaf ears, but a bit of reassurance can make them feel much better about themselves." },
    { id: 'stella', name: 'STELLA', cost: 'Costs -3 FP', birthplace: 'The Unterseeisch', signature: 'Smarts +', otherPowers: 'Healing Bits, Guardian Angel, Material Transmutation, Capable, Trainer', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c8.png', description: "Stella's mother could frankly be called a nag, but generously be called a perfectionist. And perfect her she did. Average grades of 98, could play several instruments and three sports by 5, ran her own small company by 8... and all at the cost of a normal childhood. The upside to this is that she usually does things perfectly, and is thus happy as a clam. The downside is that if almost anything she's doing is even slightly imperfect, she becomes overwhelmed with anxiety." },
    { id: 'bianca', name: 'BIANCA', cost: 'Costs -3 FP', birthplace: 'The Unterseeisch', signature: 'Superpowered Mind', otherPowers: 'Sensory Master, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c9.png', description: "She grew up until now as a lighthouse operator with her father... and became just as drab as her old man, I must say. Can you imagine sitting around on an empty island staring at the sea for a decade? I'd go mad! But it accustomed her to a very slow and quiet lifestyle, so she really struggles to keep up with the hustle and bustle of school life. Smart and witty, though, that doesn't mean she can't find her way in social circles. She speaks her mind in ways that will make people think, 'What did she just say?' Reading books for her is fun and loves spending time with her friends, but isn't one for conversation. 'Let's be what some people consider to be good friends,' she'd say." },
    { id: 'estrella', name: 'ESTRELLA', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Speed +', otherPowers: 'Psychic Force I, Quest, Twitch, Energy Channel, Sonic Boom', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c10.png', description: "Her one dream was to become a professional Segalanya racer, and she made great strides... until she hideously embarrassed herself while demonstrating her skills to an industry bigwig. No matter what, you can't seem to get any details about what actually happened -- people just make vague allusions to the 'gryphon incident' while giggling to each other. Whatever happened, it convinced her her dreams were dashed forever, and she's gotten all pouty and mopey and melodramatic about it. " },
    { id: 'siouxsie', name: 'SIOUXSIE', cost: 'Costs -2 FP', birthplace: 'Valsereth', signature: 'Pyro/kinesis II', otherPowers: 'Plasma Shells, Weaponsmith, Psionic Strike, Strength +, Shift, Rubber Physiology', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c11.png', description: "Describing herself as a missionary from the mysterious 'Ninth Dominion' beneath Mount Bearmunk, Siouxsie is ever-too-eager to preach the perfection of her fiery god Obian. She's quite a happy-go-lucky girl, even in cases where it's extremely inappropriate to be so -- it's quite unnerving to watch her prance about so cheerfully as she serves the flesh from her enemies. She considers Blessings to be a blessing, restricting their use to be sanctimonious. She loves destruction and is always up for a good scrap, so expect her to go out and show off her destructive power to anyone who'll watch." },
    { id: 'chandra', name: 'CHANDRA', cost: 'Costs -5 FP', birthplace: 'Valsereth', signature: 'Self Duplication', otherPowers: 'Plasm, SWIFT, Invisibility, Psychic Force, Superhuman, Sensory Master, Energy Channel, Personification', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c12.png', description: "Raised by a clan of famous treasure hunters, and already following in their footsteps, she is known for having acquired a staggering amount of valuable enchanted artifacts despite her young age. Smart and talented enough to get by with modest passing grades for near zero effort, as she believes the best way to learn is first-hand experience, and likes to skip classes to go find out treasures and quests -- half of which lead her to glory, and the other half lead her to a thorough scolding by the headmaster after she gets herself into trouble yet again." },
    { id: 'illuse', name: 'ILLUSE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Psychic', otherPowers: 'Hypnosis, Psychic Force II, Vampire, Spirit Medium, Fata Morgana, Thoughtseize, Lucid Dreamer, Memory Lane', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c13.png', description: "Dismissed as a mere urban legend by most students, Illuse seems to be the spirit of a slain mage reborn into a physical body with the intent of being added to the harem of a quite crude necromancer -- who, instead, died herself and became a myth of a succubus-like creature. It's a mysterious creature, but seems to be seen by strangers, usually acting in an invisible poltergeist, or sometimes appearing in people's dreams. Playful and mischievous, mobs of bullies around campus are often subject to pranks by some unseen force few will believe exists." },
    { id: 'xena', name: 'XENA', cost: 'Costs -3 FP', birthplace: 'Gohwood', signature: 'Subatomic', otherPowers: 'Ice, Cold II, Speed +, Aquatic Force, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c14.png', description: "This one's a real stoic, always as cool as that sword she swings around. That's how everyone was so surprised to find out she was actually a Knight of Snowdrake, dedicated to protecting the whole region... but there was nothing they could do once three grimsvoyers showed up. I have to imagine she's upset, deep down, after watching her home be wiped away. She still works basically 24/7 -- leisure is a foreign concept to her -- yet she somehow still finds the time to do nice things for her friends to make their lives easier. She projects an aura of prim and proper, and is fastidiously organized, dedicating every moment to self-motivation." },
    { id: 'rosalind', name: 'ROSALIND', cost: 'Costs -3 FP', birthplace: 'Gohwood', signature: 'Fire/Smoke', otherPowers: 'Crowd Control, Material Transmutation', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c15.png', description: "The royal magus images of Gohwood don't participate in the same foster program as regular mages, so we can't quite be sure of her family's goings-on. From what we've been able to gather, they're using Rosalind here as a type of girl used to having an army of servants, and is struggling to come to grips with the fact the real world isn't quite like life at the Maylead palace. She's set to inherit the entire ancient Gohwood monarchy, after all! So she can come off as a little bossy and prissy, I must admit." },
    { id: 'ruby', name: 'RUBY', cost: 'Costs -4 FP', birthplace: 'New Palisade', signature: 'Smarts +', otherPowers: 'Technomancy, C R A Z Y, B P Siphon, Overdrive, Healing Bits, S Manual Override, Healing Array, S Domain, Melee Weapon, Sabotage, Metal Shell, Grey Goo, Strength +, Incredible Will', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c16.png', description: "Sporty and utterly competitive, Ruby hopes to become the absolute best at everything she does. She's one of the top Mazball players at her age level, even though she often gets into trouble due to her frequent showboating and overestimating her own abilities. She despises being a loser, and she'll often pout and can send her enemies flying across the entire field! Even so-pragmatic, she's the ideal choice of friend -- both of you pushing eachother to work harder and get better and better. With others, though, she can have a short temper, especially if she gets tired from a hard training." },
    { id: 'cordelia', name: 'CORDELIA', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Far-field', otherPowers: 'Technomancy, Charisma +, Healing Bits, Defensive Circle, Guardian Angel, Rejuvenating Bolt', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c17.png', description: "This one scares me a tiny bit! She tests highly for antisocial personality disorder... In other words, a sociopath, meaning she can't feel empathy for others. That doesn't mean she's evil! Just a bit... detached. It doesn't help that her parents are especially given her young age. If you're injured, she's very enthusiastic about cutting you open and fixing what's wrong. Maybe too enthusiastic. Around most people, she takes up a very polite, demure personality. It's chillingly convincing. Her real self is quite, well, cynical, with a dry wit and a pitch black sense of humor. She's not afraid to speak her mind, and will be the first to call out things others consider sacred, which can be useful if you want a friend who can be very frank and critique. " },
    { id: 'anna', name: 'ANNA', cost: 'Costs -2 FP', birthplace: 'New Palisade', signature: 'Bubble', otherPowers: 'Forcefield, Energy Channel, Sonic Boom', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c18.png', description: "Anna is no typical mage, but a Distortion -- her power comes not from the Mother, but from a glitch in reality. Namely, anything she truly believes in becomes real. This may sound scary, and indeed it is, but due to a combination of magic, meditation, and her strange psychology makes her impossible to intentionally fool. Trust me, a team of rather unscrupulous scientists tried their best, and they were rewarded for their efforts only by getting slaughtered by Anna's rather disturbing 'imaginary friend', Mr. Muggins. Now fostered by the state, Anna sees the 'world of mages' as a school, a job, and is a bit of a weirdo. When compared with you, she's super excitable, bubbly and affectionate, but basically impossible to understand. She prefers to express herself by making paintings and giving hugs and gifts -- the universal languages." },
    { id: 'stacy', name: 'STACY', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Weaponsmith', otherPowers: 'Master Mechanic, F Tinker, S Overdrive, I Am Not a Weapon, Melee Weapon, Master Armor', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c19.png', description: "Pfft, oh my gosh. She's so adorable walking around with a 20mm rifle the same size as her. She's grown into it, I'm sure. Her mom was a hardcore prepper, one of those types who think society will collapse in a century, so Stacy has been undergoing brutal military training since she was a toddler. But school has finally afforded her an opportunity to escape, but she struggles fitting in. She can tell you everything about the history of firearms, for example, but nothing about buying clothes or doing schoolwork or even just how to interact with her fellow mages. Shy and a quiet, a part of her fantasizes about what it's like to be a more pretty girl and get to wear cute dresses. She'll be deeply happy if you help her explore her femininity and get her to be more happy to gush about them for hours." },
    { id: 'meryll', name: 'MERYLL', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Beastmaster', otherPowers: 'Empathy, Rejuvenating Bolt, Defensive Circle', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c20.png', description: "The school keeps getting noise complaints about her dorm room -- it's like an entire zoo in there! She's got everything from fluttering little fairies, to three-headed snakes, to a kappa of all things, although she seems most attached to a big, overgrown spider named Charlotte. She's a kind and compassionate girl who loves all animals and will take any stray she finds, which means she is often in trouble with the school. But, she is also very good with them, and can often be found helping other students with their familiars." },
    { id: 'zorreth', name: 'ZORRETH', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Fortuna/Humanity II', otherPowers: 'Foresight, Speed +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c21.png', description: "She disappeared off the grid long ago, and was presumed dead. Then, we found out her parents were actually messily devoured when she picked a fight with a pair of dragons, who proceeded to adopt 'Zorreth'. The school managed to work out a deal to let them live here, so she's set on becoming a Dragon Lord herself and is eager to be a good 'daughter'. She can be a simple girl who loves to read and have fun, and transforming into her 3 story tall draconic form and causing a huge mess. She can be placated with shiny things to add to her 'hoard', which can be as simple as a marble or a button." },
    { id: 'ayuzawa', name: 'AYUZAWA', cost: 'Costs -3 FP', birthplace: 'Jipangu', signature: 'Blessing', otherPowers: 'Strength +, Charisma +, Speed +, Quick Change, Quick Change II, Defensive Circle, Phase Shift', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c22.png', description: "Oni are extremely rare and benevolent yokai that evenly choose a lucky newborn mage to fuse with, offering them immense powers in return for enlisting them in the oni's eternal war against other sorts of yokai. Not that Ayuzawa, being the goody-two-shoes hero type she is, needed any prodding to dedicate herself to defending her beloved school against its spiritual assailants. President of the student council and a few other clubs, and prospective valedictorian of her class, no one has as much school spirit as she does! Given her track record, she's probably act like a supportive big sister, giving you advice, making sure you're safe and packing your lunches. You're going to have to set some boundaries if you don't want her babying you. If you don't, she might take over your whole life. I think she is responsible, almost overly so. She's a bit of a mother hen." },
    { id: 'momoi', name: 'MOMOI', cost: 'Costs -3 FP', birthplace: 'Jipangu', signature: 'Telekinesis', otherPowers: 'Humanity I, Psychic Force I, Oniromancy, Thoughtseize, Lucid Dreamer', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c23.png', description: "She's taken full advantage of Jipangu reverence for mages, living in her massive shrine in the woods and calling herself a goddess of the Hachimon -- sitting on a bean bag throne and being hand-fed snacks by her dutiful supplicants, the whole shebang. Smug and playful, it seems she has decided to use her claim to the title of 'goddess' to goad people and get a rise out of them. She devises little challenges to test whether you are yet worthy to be her 'right-hand mage'. Hailing from a looming line of kitsunes, the protection of nature is always her top priority, and defiling her forest is a quick way to get on her bad side. If she furies into a large, white-furred nine-tailed fox when fighting off invaders. Her human form is usually spent a half-hour day grooming her tails in the day light. She gets very grumpy and pouty when someone denies her divinity. She likes spending quiet foggy mornings together in the woods drinking sencha tea." },
    { id: 'licenda', name: 'LICENDA', cost: 'Grants +7 FP', birthplace: 'Jipangu', signature: 'Flower/of Blood', otherPowers: 'Life Drain, Spirit Channel, SpectralForm', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg2/c24.png', description: "I must strongly caution you on this one. Poor Licenda here is as broken as a person can be, a complete shell of her former self, barely ever even speaking. Years ago, she emerged the only survivor of a kidnapping victim of a deranged sexual sadist of a necromancer, with all of her tortures still up for everyone to 're-enact' in their mind. The things they did to her were expunged from all records, and most who've heard the details opted for a memory wipe rather than live with that terrible knowledge. She isn't allowed to, despite this. Outside of the Sinthru covens, these sorts of things have never happened since the Forsaken Age, thousands of years ago! Perhaps our reality is still devolving... It seems she's still followed by the ghost of her past -- literally. Most spirits are easily dispatched, but this one is completely unprecedented in its power and violent nature. There's technically no evidence of any connection, but... I feel I must warn you a few people who've hung around Licenda have disappeared under mysterious circumstances. Some suspect that the spirit has driven her to do the unspeakable. Be on the lookout for the seeming pleasure of their captors. I don't even remember what her name is." },
];

export const CUSTOM_CLASSMATE_CHOICES_DATA: CustomClassmateOption[] = [
    { id: 'custom_classmate_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_classmate_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_classmate_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];