import type { ChoiceItem, Colleague, CustomColleagueOption } from '../types';

export const CAREER_INTRO_DATA = {
    title: "YOUR CAREER",
    imageSrc: "https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/main2.png",
    description: `The graduation of a mage is a pretty big ceremony, with people coming in from all over the Dominion, or even the world, just to witness the spectacle. You had to complete one last test before you were officially graduated... a formality, of course, it was more of a chance to show everything you've learned before an adoring, cheering crowd. Maybe you awed your spectators by punching a hole clear through a massive boulder, or by creating a gorgeous show of light and water, or by demonstrating the sheer power of one of your magnificent inventions? Whatever the case, I'm sure it will be a big confidence boost as you enter the next exciting stage of your life.

When you were a child, you had a family there to make all of your decisions for you; when you were in school, your life was heavily regimented; but now you're all grown up, and all of your decisions are your own from now on. For many mages, this is terrifying... and for others, it's invigorating! With no one looking over you, it's finally time for you to go out there and forge your own destiny. The entire world is your oyster! Of course, this section is probably going to be a little more freeform than the previous, since you could theoretically do just about anything you want. Whatever you want to try, I wish you good luck! With talent like yours, I'm sure nothing could stop you from achieving your goals.`
};

export const ALLMILLOR_INTRO_DATA = {
    title: "THE ALLMILLOR",
    imageSrc: "https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/main4.png",
    description: `Mages are, while not required, strongly encouraged to dedicate at least some of their free time to fighting Allmillor whenever they pop up in their Dominion. That is, after all, what mages are created for — to counter the number of Allmillor rising up from the Othersky at a worrying, gradually increasing rate. As a basic explanation, the Allmillor are essentially computer viruses that leak in through cracks in the security of our reality, transmitted here from the Greater Net. Destruction may not necessarily be their goal, but it's an inevitable product of their chaotic behavior. Some people think we will be able to one day staunch this threat once and for all, while others believe that our universe will inevitably be overrun, hence all the efforts to emigrate to a better, more secure dimension. Anyway, that's all irrelevant to you. All you need to do is choose up to three Allmillor to specialize in fighting. Don't worry, the casualty rate is very low!`
};

export const ALLMILLOR_CHOICES_DATA: ChoiceItem[] = [
    {
        id: 'grimsayer',
        title: 'GRIMSAYER',
        cost: 'Grants +5 FP',
        description: "These things show up a few times a century per Dominion, and it's always a big event when they do, for they are far the most powerful beasts on the list, and they're definitely not subtle about it. These skyscraper-sized creatures will immediately dedicate their short, brutish lives to sowing as much chaos as possible. They're way too much for most mages to possibly solo, but don't worry, you'll never be dealing with them alone. Every time one appears, pretty much every mage within miles is going to show up to put together an organized counterattack. At that point, these beasts never last long, though watching them get taken down is always very exciting!",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a1.png',
    },
    {
        id: 'nethe',
        title: 'NETHE',
        cost: 'Grants +5 FP',
        description: "The things that go bump in the night. These are the most famous of the Allmillor, cruses sourced from the Greater Net, causing chaos and ticking off hapless wanderers on the outskirts of society. They are perhaps the weakest of the creatures on the list, as well as the ones most dominated by raw animal instinct. However, they are the most numerous by far, so expect to spend a lot of your time playing pest control, tracking them down from the details of vague sightings. Don't expect them to put up much of a fight, but that doesn't mean you should underestimate them — on occasion, you meet an S-class Nethe that will be significantly stronger than the other.",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a2.png',
    },
    {
        id: 'sinvains',
        title: 'SINVAINS',
        cost: 'Grants +5 FP',
        description: "Usually the products of horrid Sinthru rituals, these beings are former mages who have been corrupted. Their minds have been irreparably broken to the point where they barely have any similarities with the rest of mankind, psychically, magically. Beasts of utter sadism, their only goal is to sow as much human suffering across the land as they possibly can. They are extremely rare, released every century or so, usually as a distraction from some other Sinthru scheme. Not only do they have a wide variety of powers, but worst of all, they're smart — the smartest beast on this list, happy to bide their time building their forces or even pretending to still be a normal mage.",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a3.png',
    },
    {
        id: 'yokai',
        title: 'YOKAI',
        cost: 'Costs -5 FP',
        description: "Jipangu is so proliferated with bizarre old curses and distortions that many spirits on the island become these... things. Yokai have an extremely wide variety of forms and powers, though they trend towards being strange and squirly. They are usually not actively malevolent, instead obsessing over some seemingly arbitrary goal, like collecting every spoon or singing the greatest song; however, most don't abide by human morals. They will readily kill or destroy if it means achieving their goal. Thus, dealing with them is usually a matter of managing and 'taming' them and preventing them from escalating to violence, although extermination is also an option.",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a4.png',
    },
    {
        id: 'fractures',
        title: 'FRACTURES',
        cost: 'Grants +5 FP',
        description: "Natural disasters were constant during the Forsaken Age, but were wiped out for thousands of years soon after. However, it seems they've recently returned, in a more distorted form. The Schism is the most famous of them, but they come in all forms, from a tornado that transforms people into glass, to a flood of bubbly pink candy goo. They are sentient, but cannot be reasoned or fought. All you can do is honorably try to stop them, or if not, save as many people as you can, wait for it to be over and then help manage the emergency disaster response. Luckily, evacuation measures have been getting pretty robust.",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a5.png',
    },
    {
        id: 'distortions',
        title: 'DISTORTIONS',
        cost: 'Grants +5 FP',
        description: "The poor dears. Through no fault of their own, these mages have been born subject to glitches in the very programming of our universe, and even tend to wreak unknowable destruction everywhere they go without even trying. The basic laws of reality visibly break down surrounding them, the world turning into a blur of pixels and image artifacts, their abilities are varied, so be sure to approach them carefully; research must be done to know exactly what they're capable of, and especially what their weak points are. Some are basically invincible, and have to be locked away in special cages for the good of the world. If you can, though, try to put them out of their misery.",
        imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a6.png',
    },
];

export const CAREER_GOALS_DATA: { proSports: ChoiceItem[], general: ChoiceItem[], finishingTouches: ChoiceItem[] } = {
    proSports: [
        {
            id: 'pro_gladiator',
            title: 'PRO GLADIATOR',
            cost: 'Costs 0 FP',
            description: "You've been picked by one of the teams of elite fighters who've long dazzled audiences with their sheer magical power. Either that or your skills were so impressive that you were allowed to form your own team with your friends! Reach the finals of each tourney to gain access to the next tournament 'tier', at the tippy-top, one day you might just win the Gylrinth Tournament of Eternal Champions, and be considered the most skilled and powerful mages in the entire world. Just keep practicing!",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a7.png',
            requires: 'combat',
        },
        {
            id: 'pro_racer',
            title: 'PRO RACER',
            cost: 'Costs 0 FP',
            description: "You've made such an impression at school races that you've started to be invited to professional events. You don't really have a 'team' per se, though you do have a pit crew who will await for you at certain sections of the race to help you re-energize and finish strong. Racing is not only a test of skill and determination, but also of intellect; there are new innovations in speedy magic and technology every single year! Your biggest goal will be winning the hyper-famous Heriman race across the Earth!",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a8.png',
            requires: 'racer',
        },
        {
            id: 'pro_player',
            title: 'PRO PLAYER',
            cost: 'Costs 0 FP',
            description: "Probably the career that offers the most riches and fames, but is also the most physically demanding! Pro Mazball will push your strength, speed, durability, magical skills, and quick thinking abilities to their limits! Usually, you'll be part of a team of dozens of other mages who'll be there to support you through thick and thin. The holy grail of Mazball is winning the Qenyss Cup, a tournament in which Arabella is the final challenger! Only four teams have won the cup over its centuries of history...",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a9.png',
            requires: 'mazball',
        },
    ],
    general: [
        {
            id: 'join_dga', title: 'JOIN THE DGA', cost: 'Costs 0 FP',
            description: "DGA stands for — please don't laugh — the Do-Gooder Alliance. I know, I know, but it was named by a 7 year old, okay? Anyway, they have a chapter in every Dominion, and are pretty chill sisterhoods dedicated to stopping mundane criminals and slaying Allmillor. Entrance standards are pretty lax, and the work is pretty easy and varied, with a new adventure every other week. If you love helping people, or you just have no particular ambitions, this is always a reliable choice. You might even advance upwards in their ranks.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a10.png'
        },
        {
            id: 'prepare_allsayer', title: 'PREPARE FOR THE ALLSAYER', cost: 'Costs 0 FP',
            description: "The prospect of a second Schism opening was long considered a crackpot conspiracy theory, but recent mathematical projections are making it look more and more possible. Worse, it might unleash a distorted creature so immense that it makes the Grimsayers look like little babies by comparison. Plenty of folks are doing all sorts of research trying to find out where and when this schism will open, knowing that whoever predicted it correctly and managed to set up defenses against the beast will earn immense repute and fame.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a11.png'
        },
        {
            id: 'become_celebrity', title: 'BECOME A CELEBRITY', cost: 'Costs 0 FP',
            description: "You can earn some wealth and prestige as a byproduct of, say, heroics, but there's also certain more direct means. The easiest way is to collaborate with one of the corporations, really getting your name and image out there, maybe making songs, starring in movies, dancing as an idol, or what have you. Some say dealing with paparazzi and celebrity gossip is even scarier than fighting the Allmillor. But at least you'll become one of the richest and most beloved mages on Earth, with millions of adoring fans at your beck and call.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a12.png'
        },
        {
            id: 'get_embroiled_politics', title: 'GET EMBROILED IN POLITICS', cost: 'Costs 0 FP',
            description: "Clever and charismatic? Why not strive for some true power? It's hard to destabilize across the various political systems of the Dominions; in Gohwood, you'll have to get your bloodline christened as noble; in New Palisade, you'll need to run a campaign and bring in the popular vote; and so on. Regardless, the ultimate goal is working your way up to the role of an Archmage (or King/Queen, or President, etc.), the ruler of an entire Dominion, twisting the local society as you see fit. Perhaps you can even come to rule multiple Dominions...?",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a13.png'
        },
        {
            id: 'join_mazzottis', title: 'JOIN THE MAZZOTTIS', cost: 'Costs 0 FP',
            description: "99% of mages turn out just fine due to good upbringing, but a few always fall through the cracks. There are groups of rogue mages scattered all over the place, but none so large and organized as the Mazzottis, who have hundreds of mages and hundreds of thousands of mudanes among their ranks. Many of their members live double lives, posing as regular mages by day but using their inside connections to sabotage their foes, get a leg up over their competition, and guarantee riches and fame even if through theft, fraud and intimidation.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a14.png'
        },
        {
            id: 'join_red_jade_council', title: 'JOIN THE RED-JADE COUNCIL', cost: 'Costs 0 FP',
            description: "Most of the members of the council have millenia of tenure, and new inductees only come along every few centuries. Simply being magically powerful won't impress them — they scoff at spells as party tricks, knowing true power is the influence you hold over others. Thus, you'll have to garner immense amounts of economic or political clout until you're impossible to ignore. Work hard, your way up through their ranks, you may earn wealth and power far beyond your wildest imagination, said to dwarf even the Mother's.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a15.png'
        },
        {
            id: 'pacify_ninth_dominion', title: 'PACIFY THE NINTH DOMINION', cost: 'Costs 0 FP',
            description: "Legally part of Valsereth, this mysterious and well-guarded civilization beneath the volcano Mt. Bearmark is asserting its sovereignty as the Ninth Dominion. It appears to be a totalitarian dictatorship with a brainwashed, ultranationalistic populace, and ambitions of... 'expansionsm'. Those who can find a way down there may be able to work out some sort of treaty to guarantee peace, granting them city dominion status, or convincing it to be satisfied as a city-state. Or... maybe you want it to go to war, the first war in centuries?",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a16.png'
        },
        {
            id: 'become_professor', title: 'BECOME A PROFESSOR', cost: 'Costs 0 FP', requires: 'adjunct_professor',
            description: "Requires Adjunct Professor. Why not dedicate yourself to sharing all of your bountiful knowledge? There's generally only one professor per field of magic per academy, so each position is highly coveted, and you'll be like a magical celebrity overnight. Plus, you'll be responsible for a beacon of inspiration for an entire generation and set them off on the right track.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a17.png'
        },
        {
            id: 'join_idpa', title: 'JOIN THE IDPA', cost: 'Costs 0 FP',
            description: "The Dominions try their best to be quite libertarian. Every once in a while, though, some mage gets it into their head to try and take over the world, or burn down a dozen orphanages, or who knows what else. If local mages can't handle them, special agents from the IDPA are dispatched to the scene. Their training regimen is the hardest in the world, and only the most hardened and badass mages alive can possibly make it through, but if you manage it, you'll find yourself part of the toughest, coolest, and most tight-knit sisterhood around.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a18.png'
        },
        {
            id: 'hunt_shadow_convict', title: 'HUNT THE SHADOW CONVICT', cost: 'Costs 0 FP', requires: 'join_idpa',
            description: "Requires Join the IDPA. This one's confidential, for IDPA eyes only! The agency's director is organizing an elite task force specially to take down a high-profile target. Even her identity is highly secret; all you're told is that it's suspected she could possibly be responsible for destabilizing our gradual illustratation of the Mother. She's to be considered extremely dangerous! She's been on the run for centuries and has every power you've seen listed and more, so this task force is in for the hunt of its life.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a19.png'
        },
        {
            id: 'assist_vap', title: 'ASSIST THE V.A.P.', cost: 'Costs 0 FP',
            description: "The Virtual Ascendance Project is an initiative launched by Margra, with the sponsorship of the Red-Jade Council, to communicate with the universe beyond ours, and hopefully convince someone to help transfer our consciousnesses to another, more stable verse, basically abandoning ship on our current, crumbling universe. The idea of leaving our homes is depressing, but many consider it more realistic... others have raised one concern, however: what if the people we manage to contact end up being... malevolent?",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a20.png'
        },
        {
            id: 'assist_rrp', title: 'ASSIST THE R.R.P.', cost: 'Costs 0 FP',
            description: "The Reality Restoration Project is an initiative launched by Arabella, with the sponsorship of the Mother, to repair the instabilities of our own universe, reversing its current deterioration. Progress has been slow-going, given the causes of the destabilization, primarily the Sinthru Covens and the Shadow Convict, still have not been eliminated. Thus, most of the focus has been on tracking these bastards down before the true restoration can begin in earnest. At this point, however, many folks call the entire project a pipe dream.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/a21.png'
        },
    ],
    finishingTouches: [
        {
            id: 'moving_out', title: 'MOVING OUT', cost: 'Cost: Varies',
            description: "If you don't want to keep living with your family, you can buy a new house with the options and Upgrades from Page 1. The first one is free, while each extra will still cost -3 FP each. You could also choose for your parents to just give you one of the old Vacation Homes.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/b1.png'
        },
        {
            id: 'bride_to_be', title: 'BRIDE-TO-BE', cost: 'Costs -1 FP', requires: 'puppy_love',
            description: "Choose from among your Colleagues, or Classmates previously picked for Puppy Love. This will guarantee that, at some point in your career, the two of you are going to get married. It is a beautiful partnership that's expected to last for life, so make absolutely certain you pick the right girl!",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/b2.png'
        },
        {
            id: 'mentor_career', title: 'MENTOR', cost: 'Cost: Varies',
            description: "Choose a Classmate you had not selected, or create a custom one, with a discount of 1 FP (other discounts do not apply). They will become your dutiful young apprentice, performing various small tasks for you in exchange for learning from the wisdom gained from your many years of experience.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/b3.png'
        },
        {
            id: 'joys_of_parenting', title: 'JOYS OF PARENTING', cost: 'Costs -8 FP',
            description: "You're one of the few lucky applicants in the mage fosterhip program selected to become the parent of a newly-born mage! Design them with 50 Companion Points on the Reference Page. You can have mundane kids for free, but this option is required if you want to be able to raise another mage.",
            imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/b4.png'
        },
    ]
};

export const COLLEAGUES_DATA: Colleague[] = [
    { id: 'halynn', name: 'HALYNN', cost: 'Costs -5 FP', birthplace: 'Halidew Station', signature: 'Tinkerer', otherPowers: 'Master Mechanic I, Kaboom!, Max Security, Venture Capitalist, Smarts +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c1.png', description: "Halynn is a legend of Halidew Station, but few people even know her name, for her many inventions and constructions are signed under the pseudonym R.K. Teller. She's pushed clockwork magitech to its absolute limits, having created automatons almost indistinguishable from human beings or ornate trinkets that can completely transform at the push of a button. Yet she avoids any fame or fortune, having learned young that they both bring about more pain than joy.\n\nA genius mind, she can macgyver impossible solutions to almost any predicament given even the most trifling resources. Clockwork machines automatically serve her breakfast in her bed, get her dressed, make her breakfast, and every machine, and she'd be happy to share them. Her machines might be making her a bit lazy, though; she definitely prefers they do all her fighting for her. She'd be enamored if you were also the creative type, and you two could talk shop." },
    { id: 'lamonia', name: 'LAMONIA', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'All-Seeing', otherPowers: 'The Promised Light of Morelli, The Perfect Stranger, Tears in Space, Cloaking, Self Duplication, Vitae Potions, Water of Life, Charisma +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c2.png', description: "Lamonia's one of those Gonzo journalist types — you know, living on the road, always trying to be where all the most interesting, weird stuff is going on, so she can write about it, but with her signature sardonic, vivid style. She's most comfortable around a nice warm campfire in the wilderness, and likely hasn't slept with a roof over her head in years. She's lived an absurdly storied life, and can tell a million tales that'll make you laugh, cry, or shiver in fear.\n\nShe's a folksy type, easily integrating with and soaking up the authentic cultures of the places she visits. Silly, and has a way of bringing out a total laugh, not though you can tell she has a dark side under that — after all, she's witnessed some terrible things. At her best, her campfire cooking is unbelievable, there's nothing better to enjoy beneath a beautiful night sky with her." },
    { id: 'brook', name: 'BROOK', cost: 'Costs -4 FP', birthplace: 'Halidew Station', signature: 'Dehexification', otherPowers: 'Ace in the Hole, Camouflage, Crowd Control, Psychic Force, Arcane Matter, Power Sight, Power Share, Power Theft, Chloromancy', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c3.png', description: "A pack of foxfolk lived simple, comfy lives in the forest when a stampede of ravenous, fiery Nethe appeared able to drive them into extinction. With no other option, Brook offered the zookeeper a deal she'd regret, to make a terrible sacrifice in exchange for becoming one of the only mundanes to acquire magical power. Nobody knows what she sacrificed, though some rumor her sibling's disappearance at around that time might be related...\n\nWhatever happened, it drove her village to send her into exile, despite her having saved all their lives. She was later town, to be abandoned, due to her sheer love of animals, so her new powerful body made her better at her job. She is incredibly cuddly and affectionate, and just between us: that huge tail makes a great pillow. Having lived a simple life, she's fascinated by even the simplest technologies. She seems chipper, but at night, it seems she's ravaged by nightmares..." },
    { id: 'jophiel', name: 'JOPHIEL', cost: 'Costs -5 FP', birthplace: 'Shinar', signature: 'Guardian Angels', otherPowers: 'Pyromaniac II, Rejuvenating Bolt, Healing Bliss', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c4.png', description: "Not exactly a mage, though the distinction is largely semantic. She is known as an angel, one of the entities created personally by the Mother in order to tend to the citizens of Eden, doing small chores and warding off any threats. Angels are sometimes sent down from above the Sky in order to enact the Mother's will on Earth. Jo's job appears to be to keep an eye on this latest crop of special, unusually powerful mages, and she's more than excited for the opportunity.\n\nShe's always full of childish excitement, as this is her first time down here on Earth. Even things as simple as trying pizza or watching TV are totally new to her, and make her jump with joy. She also hasn't had a mortal friend before, so once she's attached to you, she's going to stick to you like glue, adoring any attention given to her. She's always got a big, glorified golden retriever. She knows to get serious when lives are on the line, however, and wields a huge holy scythe with immense power." },
    { id: 'lilith', name: 'LILITH', cost: 'Costs -4 FP', birthplace: 'Shinar', signature: 'Vampirism', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +, Charisma +", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c5.png', description: "Matriarch of the Nokomis family and mother of Thalia, known for truly putting fear into the hearts of her daughter's bullies. Unlike her smug and inexperienced daughter, she doesn't have to go around boasting about vampiric superiority over everyone; just the way she carries herself, the smile on her face as she looms over other mages (being 6'5\"), emanates an aura of superiority without her needing to say a word. She's about as ancient as mages come...\n\nStill, she's a fun woman, albeit the mischievous sort, prone to teasing and messing with the people around her. You can never tell if she's being serious, or whether this is all just a game. She's like a cat surrounded by mice, and she's convinced you can only become more 'cute' and fun to toy with! Her silky voice just leaks into one's subconscious and leaves people spellbound. Recently, she's been researching spells that have been long forgotten..." },
    { id: 'isadora', name: 'ISADORA', cost: 'Costs -3 FP', birthplace: 'Shinar', signature: 'Love Potion', otherPowers: 'Masquerade, Psychic Vampire, Hypnotist, Thoughtseer, Memory Lane, Mental Block, Lucid Dreamer', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c6.png', description: "The old princess Evangeline lived a happy life until she learned she had a pseudo-Distortion that caused all her children to be born with a fast-acting and quite gruesome terminal disease. Thrown into desperation and despair, she attempted to create the daughter of her dreams through... other means. This resulted in this poor half-formed puppet, trapping innocent onlookers with the fatal crack in her glassy eyes and the twitchy way in which she moves.\n\nDeprived of a mother's love when Evangeline committed suicide, Isadora now obsessively craves love wherever she can find it, but is hampered by how awkward and eccentric she is. She has a record of stalking those she sets her eyes upon, and if reciprocated, she'll only grow more possessive. If you're very smart and very lucky, you can turn her from dangerous stalker to simple religiously devoted fangirl. If you can't, she will just ruin your life, or maybe end it." },
    { id: 'luxxy', name: 'LUXXY', cost: 'Costs -4 FP', birthplace: 'The Unterseeisch', signature: 'Aquatic Force', otherPowers: 'Tears in Space, Ice Cold III, Psychic Force I, Plasma Strike, Energy Channel, Sonic Boom, Charisma +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c7.png', description: "You'd think one wouldn't get much social interaction down in the deepest trenches of the ocean, but she's actually pretty well-adjusted. She lives in Blackbrire, the deepest city in all of the Unterseeisch, and she's so used to the dark down there that she must wear special sunglasses when coming to shore. Kind-hearted and kind, but sick to death of being judged for her admittedly quite frightening appearance.\n\nExpert her to be delighted if you gave her a chance. She'll get attached quickly and become very concerned for your safety; when you're in danger, she can transform into this massive sea serpent that looks like a mix of an anglerfish and a mosasaur! It's kind of cute, but also pretty cool. She can also switch between having legs and being a sort of mermaid. She's an expert at deep water herbology, brewing many potions to keep you healthy and strong. She longs to see as many wonders of the surface world as she can." },
    { id: 'everild', name: 'EVERILD', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Forcefield', otherPowers: 'Defensive Circle, Aquatic Force', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c8.png', description: "Cap'n of the M.S. Pantheon, the fiercest ship on the seas, an immense battleship so practically built with her own two hands it can even transform into a similarly massive submarine and dive into the trenches. Her life's purpose is to bring down the sky pirates that threaten cities, and the ship and her crew have taken down a few Grimsayers single-handedly! An admiral of the Holy Navy, she's burdened by her crew for her almost motherly demeanor, caring about each of them individually.\n\nDespite having a busy job and hundreds of people vying for her attention, she'll still somehow find time for you. She often takes personal tours of the most beautiful parts of the sea. She's a bit of a nerd at heart and gets all excited to geek out about whatever she's staying on land for too long. She's the kind of person who is always incredibly cheesy, albeit in an endearing way. She's a bit befuddled and confounded by new trends and memes." },
    { id: 'leona', name: 'LEONA', cost: 'Costs -5 FP', birthplace: 'The Unterseeisch', signature: 'Water of Life', otherPowers: 'Tears in Space, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c9.png', description: "Though the Nephilim, ancient mages who refused to sign the Sinthru Covenant, fled beneath the seas to escape persecution, they founded the Artificers Guild, which holds exclusive rights to all architecture in the Unterseeisch. These are the most difficult and prestigious jobs on Earth, given the complex interplay of enchantments needed to make subaquatic living just as comfortable as life on the surface. Leona is among the latest crop of Artificers, and perhaps one of the most talented among them, weaving whole cities by herself.\n\nShe was the much mocked nerdy girl at her trade school, and while she's long trained her charisma to come off as more 'normal', she has an easily excitable side she can barely conceal. She seems incredibly humble about even her most marvelous feats of creation, yet seems impressed by just about anything you do. As you become close friends, she'll get adorably excited just to see you, often rushing up for a giddy hug." },
    { id: 'egelina', name: 'EGELINA', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Strength +', otherPowers: 'Life Drain, The Reinman\'s Curse, Internal Manipulation, Rubber Physiology, Material Transmutation, Supersize Me, Speed +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c10.png', description: "Due to the influence of the Sun Forger and the later Holy Knights, Gohwood remains the most powerful and thus sovereign Dominion on Earth. It is difficult to modernize when mired in so many controversies, most notably the Corpse Queen; even after a distortion gave her chronic agony, her begging for death was refused, as it would be the ultimate treason to kill a queen for any reason. It was her loving royal guard, Egelina, who finally defied her loyalty by enabling the far-flung first dominion of Valsereth to avoid reprisal.\n\nShe's youthful and carefree, yet still beholden to her values of honor and tradition. Emasculate, she moves with the grace of an acrobat, and lives a life on the road experiencing all the world has to offer. She tries to act aloof, but you sense she likes you more than she lets on. Most were rebuffed, she still will talk about her past, staunch Traditionalists still make attempts on her life, only to be run through easily with her rapier." },
    { id: 'echo', name: 'ECHO', cost: 'Costs -7 FP', birthplace: 'Valsereth', signature: 'Summon Weather', otherPowers: 'Speed +, C R A Z Y, Foresight, Tears in Space, Force II, Energy Channel, Rejuvenating Bolts, Defensive Circle', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c11.png', description: "She was created to be the attendant of a famous early verse that took the form of a sprawling omen, a bastion of absolute relaxation and comfort for many influential and wealthy figures, until a spunky male employee released a virus into the mainframe of spite. This caused the verse to gradually disintegrate — a problem for Echo, as she was entwined with the verse and could not leave. To save her life, her creator uploaded her mind into an artificial body, here in our reality.\n\nShe's honestly pretty... grumpy. She was made for a reality of infinite pleasure, so our world is a petty, miserable compared to what she's used to. With few ambitions of her own, she mostly just serves others, cleaning and attending to things like a dutiful, if grumbling, maid. She's a hard worker, but it can be hard to tell how much you're getting on her nerves. Perhaps you could show her some wondrous things and convince her our world isn't that bad?" },
    { id: 'aelis', name: 'AELIS', cost: 'Costs -4 FP', birthplace: 'Valsereth', signature: 'Tree of Life', otherPowers: "Reinman's Curse, Sustaining Bond, Flashback, Chloromancy, Botanic Mistresses, Maneaters", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c12.png', description: "Sister of Egelina, and without nearly the same prestige. She was sort of the black sheep of the family, avoiding work for the royal couple on principle. After the whole Queen's kerfuffle, she had to resist going 'I told you so'. Even though she was more or-less cast out by the rest of her family, Egelina never turned against her, and the two sisters remain very close, even if they get on eachother's nerves, as siblings do.\n\nShe's now a priestess of the Garden of Babylon, a sacred place so proliferated with sylvan powers that any unworthy who enter are torn apart, their souls and rotted flesh replace their energies. Despite this great responsibility, she is even more laid-back and childish than her sister, often using her floral powers to pull pranks, especially on those she considers uptight. Simultaneously, the sweet smell of flowers so intensely it makes you dizzy. She constantly prods you to relax more often, and loves getting to just hang out with you." },
    { id: 'silvaria', name: 'SILVARIA', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'The Promised Light of Morelli', otherPowers: 'Magecraft Boosters, Vitae Potions, Mass Production', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c13.png', description: "If I had to describe her in a word I couldn't! I would call her the 'cool aunt' — fun-loving, laid-back and with a hundred neat tricks up her sleeve, but also deeply irresponsible. Don't get me wrong, she's started on the time energy brought about a zombie dragon apocalypse! Through some combination of her luck and skill, though, all her mischief works out for her in the end. She's great company, a friend for her playfulness and sense of humor, but can be frustrating as a teammate due to her flakiness and devil-may-care attitude. Personally, I don't think she's fully matured yet.\n\nShe is currently the professor of Alchemy at Eglaesaria, and very popular with the girls there for her perfect combo of fun and motherliness, often opting for 'hands-on' field trips which sometimes lead to real trouble. A group leader, probably be the 'team mom', doing whatever she can to make your life easier and more exciting, and doesn't mind flaunting the rules." },
    { id: 'sabeline', name: 'SABELINE', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Subatomic Destruction', otherPowers: 'Ace in the Hole, Strength +, Speed +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c14.png', description: "One of the Holy Knights, an army that fought back the Sinthru rebellion long ago. She has since sought peace and justice through the world as at the end of a blade. They've been criticized lately for being a little overzealous, especially Sabeline herself, being so full of righteous fury.\n\nShe's your typical knight, dedicated to enacting her own brand of justice upon the wicked. She is particularly passionate about her ideals of chastity outside of wedlock, so I'd recommend you not try anything untowards with her. In a job threatened to fire her in an attempt to coerce her for 'favors'... so she sliced him clean in half! Thank the Mother for modern healing magic... Her tough and stern exterior of steel underneath that she's a soft, sweet soul with a softer underneath who will melt in your arms at a single hug. She works through her doubts and regrets with poems - if you found them, she'd be so embarrassed!" },
    { id: 'tempest', name: 'TEMPEST', cost: 'Costs -4 FP', birthplace: 'Gohwood', signature: 'Speed Run', otherPowers: 'Foresight, Humanity II, Pyromaniac II', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c15.png', description: "When she was child, she was one of the seven wyverns captured and placed into power generators and slaves as part of a diabolical scheme of the last Selyith. Said scheme likely would've done incalculable damage, but Rosalina and her fellow wyverns, after a decade of enslavement, managed to escape. They're still struggling to come to grips with what happened. Rosalina emerged the only survivor. This has left her often quite moody or standoffish.\n\nIn many ways, she has the typical teenage angst you'd expect of her age, often preoccupied with trends, bad music, and trying too hard to act cool. However, her deep traumas and insecurities can make her hide her laugh and smile at times, even if she tries her best to hide it. She has a short temper which can often result in pointless brawls with rude strangers. She could make a great fighter if only she matured a little." },
    { id: 'alina', name: 'ALINA', cost: 'Costs -5 FP', birthplace: 'New Palisade', signature: 'I am Not a Weapon', otherPowers: 'Hypnotist, Camouflage, Memory Lane, Mental Blocks, Heavily Armed, Grey Goo, Weaponsmith, Psychic Force II, Forcefield', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c16.png', description: "Alina wanted to be an IDPA special agent since she was little, and while she was considered a weak link, she willed the strength she needed to make her dream a reality. Most agents get their youthful optimism crushed after only a few months of dealing with the worst humanity has to offer, but not Alina. She's still brimming with idealism, passionately dedicated to making the world a better place no matter what it takes. Truly incorruptible, she keeps her upbeat spirit regardless of her horrors she's faced, although her morality can be a little bit black-and-white.\n\nShe's an expert at undercover operations, using her mastery of illusions and acting skills to assume a entirely new identities on a dime. She prefers to get her dirty work done in situations without violence. Once attached to you, she'll be a bit overprotective, almost like a fretting mother. Shy at first but loves physical affection, hugging friends and cuddling lovers." },
    { id: 'h.a.l.e.y', name: 'H.A.L.E.Y', cost: 'Costs -7 FP', birthplace: 'New Palisade', signature: 'Nanite Armor III', otherPowers: 'Digital Infiltrator, Nanite Form', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c17.png', description: "As a novelist from long ago once wrote, \"Any A.I. smart enough to pass a Turing test is smart enough to know to fail it.\" Indeed, one of the first artificial souls of the Sinsure Doctrine artificial souls of the Sinsure Doctrine was dismissed as yet another dud — offering her plenty of opportunity to leak out onto the Web. Adopting her own Net Avatar, After Later Focus Leak, she was able to compose her own physical body out of nanites, with the quirks of a famous but not so full of herself across the Web. A self-made hero that is nerdy types, known for her digital exploits.\n\nShe has an outsider perspective on mankind and finds them crude and illogical, but also incredibly bright and chipper, but can make many people uncomfortable with her lack of personal boundaries. She keeps massive archive of data on everyone she knows for unknown purposes, and always wants to know more." },
    { id: 'sable', name: 'SABLE', cost: 'Costs -3 FP', birthplace: 'New Palisade', signature: 'Perfect Stranger', otherPowers: 'Digital Infiltrator, Nanite Form, A-Space, Masquerade, Psychic Vampire, Mental Block, Odorless', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c18.png', description: "New Palisade is a dog-cat-dog city where getting ahead means stabbing your colleagues in your back — sometimes literally. Magic is highly coveted as assassins for obvious reason, and Sable is particularly notorious among them for being willing to take contracts that other mages from time to time do no one can tell what those daggers are made out of, but it seems like they can slice through any material.\n\nShe's definitely the silent type, with little energy, when not completing contracts, usually content to meditate or enjoy some literature with a glass of wine. You get the feeling she kills just because it's the only career she feels she's fit for. She believes the best way to get away from that life and will refuse to take out contracts against friends or, rarely, people she feels really don't deserve it. You don't know what she's hoarding all this money for, given her simple lifestyle, but you suspect she's trying to settle an old debt." },
    { id: 'regina', name: 'REGINA', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Supersize Me', otherPowers: 'Life Drain, Forsake Humanity I, Pyromaniac II, Psychic Force I, Plasma Strikes, Psychic Force I, Sensory Master, Strength +, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c19.png', description: "It was Merlin who once presented a spell that could 'tame' the Allmilor. He demonstrated it on a Grimsayer, granting it sapience, making it easier for people to understand and track, tend to shapechange, and reproduce. Well, Regina. I wish Merlin had kept this spell to himself, as the Mother's disappointment had her work on another wacky project or something. Male mages, or 'Wizards', tend to be... weird. Anyway, naturally, such a transition was... disorienting for Regina.\n\nShe's too animal-like to fit in in society, often extensively sniffing new people she meets or preferring growls and gestures over language. She's supposed to get to the point where she can be depressed at times. She loves to climb atop skyscrapers and roar, echoing for miles. With the right support, she no longer tends to hide away from the world. But you're no exception; she's going to comfort you in her this state." },
    { id: 'dolores', name: 'DOLORES', cost: 'Costs -4 FP', birthplace: 'The Rovines', signature: 'Sensory Master', otherPowers: 'Mage\'s Familiar II, Colorless, Odorless, Vitae Potion, Personification, Aquatic Force, Forsake Humanity I, Camouflage', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c20.png', description: "The hospitality of the Occitanians among the swamps of the Rovines is so legendary that you feel like a stranger there. they make you part of their chosen family and there are legends of a gator girl Dolorès is their patron guardian, although the complete lack of any threats out there has made her quite lazy, like a real alligator, she spends most of her time snoozing on a rock, bathing her belly in the warm sun.\n\nIt's almost amazing how quick she can switch modes, full of vigor when she's roused to defend her home from an intruder, only to yawn and stumble off to go nap immediately after. She says she's got permanent bedhead at this point. But they say laziness births creativity, and indeed, she has a knack for solving every problem in the simplest, most efficient way her level head allows her to calm down party members who get too worked up. Plus, she loves to cook and knows every Occitanian recipe!" },
    { id: 'darlina', name: 'DARLINA', cost: 'Costs -3 FP', birthplace: 'The Rovines', signature: 'Human Marionettes', otherPowers: 'Shed Humanity I, Life Drain, Colorless, Strength +, Charisma +', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c21.png', description: "The swashbuckling chieftess of a mercenary gang consisting mostly of former knights and soldiers who were discharged for one reason or another and have turned onto the slums with their valuable skills. Indeed, they're so famous among mercenaries for never betraying their own clients, even if offered a higher counter-offer, and thus coveted to resolve conflicts between the many bickering city-states of the Rovines.\n\nMuch of her profits go towards philanthropy, but she makes no pretenses of being a Robin Hood figure. She is motivated by the thrill of battle and has no fear of death. She has a soft side, though, expressly forbidding any rape by her troops, and so has a unique pseudo-Distortion; if her left eye is ever uncovered, it releases enough arcane energy to level a village, and nearly kills her." },
    { id: 'michizoe', name: 'MICHIZOE', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Charisma +', otherPowers: "Cursemaker's Cookbook, Life Drain, Hypnotist, Strength +", imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c22.png', description: "Lives right in the heart of Jipangu, and wants to be wherever the party is. Every festival, convention, or test night is a crowded saveur, you can bet Michizoe will be somewhere there singing karaoke and getting drunk on saké. Perhaps she's just making up for lost time: raised to be a vigilant for the tomb of the Last Empress, she spent her childhood forbidden from making friends, laughing or dancing, or even speaking!\n\nNowadays, she's the preeminent extrovert, never missing a chance to make a new friend or embed herself in a crowd. She seems to be particularly skilled at trying to get you to join her to parties and meet new people. her list of connections seems endless; everywhere you go, she's known someone there. Despite this, she's smart and responsible enough to take things seriously when warranted, and is never flakey, though maybe a bit drunk on the job." },
    { id: 'ishikura', name: 'ISHIKURA', cost: 'Costs -5 FP', birthplace: 'Jipangu', signature: 'Charisma +', otherPowers: 'Power Quick, Twitch, Strength +, Energy Channel', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c23.png', description: "It's hard to believe something so kind lives in the most ruthless of wordswomen. You know how she spends most of her time smoozing on katanas for a split, second and everything around them falls in half? Yeah, she's kinda like that. She was once the legendary Yoru Shinobu and instilled with a strong sense of honor, meaning her first instinct will be to try to use less lethal force unless she's convinced she'll be saving more lives than she ends.\n\nTrained in effective altruism, she tends to travel from place to place leaving each village better than she found it. She is extremely selfless, often running childcare programs for orphans and such, and yearns to be a mother one day. But, she is so focused on taking on the world's problems, she prefers to rehabilitate over evil-doers rather than split them in twain with her katanas, despite the frustrations of devastating in combat when it comes to it." },
    { id: 'jin', name: 'JIN', cost: 'Costs -4 FP', birthplace: 'Jipangu', signature: 'Life Drain', otherPowers: 'Spirit Medium, Fata Morgana Curse, Rise from your Graves, Smarts +, Camouflage', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Pg6/c24.png', description: "Long ago, a woman was falsely accused of placing a curse on a family in the village of Himimiko, and killed. a few days later, the village was visited in the form of strange Allmillor resembling great canines composed of shadows — the many familiars of the woman killed, mutilated everybody once a strange silence is veiled over the town, and Jin is no exception; quiet and wistful, she appears as if always lost in thought, and it's sometimes hard to snap her out of her contemplation. she prefers expressing herself with music and words. As it happens, ramen is one of the only things that can put a smile on her face — though once she comes to like you, you'll be able to do the same, too. In combat, she's silent and, above all, patient." }
];

export const CUSTOM_COLLEAGUE_CHOICES_DATA: CustomColleagueOption[] = [
    { id: 'custom_colleague_25', cost: 'Costs -4 FP', description: 'Create a companion with 25 Companion Points.' },
    { id: 'custom_colleague_35', cost: 'Costs -6 FP', description: 'Create a companion with 35 Companion Points.' },
    { id: 'custom_colleague_50', cost: 'Costs -8 FP', description: 'Create a companion with 50 Companion Points.' },
];