import type { CompanionOption } from '../types';

export const COMPANION_INTRO = {
    imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/main.png',
    description: "You can decide what they look like on your own. You can also choose contradictory personality traits, if you want. Note that companions can't have their own companions, automatons, puppets, etc."
};

export const COMPANION_CATEGORIES: CompanionOption[] = [
    { id: 'mage', title: 'MAGE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/c1.png', cost: 0, description: "Just a regular human being, created by the Mother herself every Theosis Day! They tend to possess great powers, but also have their own goals, opinions and desires. Whether these align or conflict with yours can be decided in the Relationship category just below. Pretty fun people usually, though!", requirement: 'Required if no other conditions are met' },
    { id: 'puppet', title: 'PUPPET', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/c2.png', cost: 0, description: "Created through a complex and advanced bastardization of the process through which the Mother creates mages, these creatures are virtually indistinguishable from a human, aside from their general uncanny valley vibe and the sheer diligence with which they serve their creator.", requirement: 'Requires, and is required if, Human Marionette/Verse Attendant' },
    { id: 'automaton', title: 'AUTOMATON', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/c3.png', cost: 0, description: "Human-like entities with a wide variety of possible appearances created by imbuing an advanced machine with an artificial soul. They are highly durable and intelligent, but their true sapience is a subject of debate, and the way they express their emotions can feel either dulled or forced.", requirement: 'Requires, and is required if, Roboticist II' },
    { id: 'undead', title: 'UNDEAD', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/c4.png', cost: 0, description: "The rotting remains of a mage who once lived brought back to life, generally striking disgust and fear into the hearts of all who witness them. Their intimidation factor is immense, and they benefit from increased regeneration from cuts and blunt damage. Expect funny looks, however, at the very least.", requirement: 'Requires, and is required if, Undead Thrall' },
];

export const COMPANION_RELATIONSHIPS: CompanionOption[] = [
    { id: 'frenemies', title: 'FRENEMIES', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/r1.png', cost: 0, description: "Either due to conflicting beliefs and personalities, or mere circumstances, you two will be at odds when you first meet. You'll still cooperate, but expect to get on each other's nerves. It won't be impossible for you to become better friends, but you'll have to make a genuine effort." },
    { id: 'friends', title: 'FRIENDS', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/r2.png', cost: 5, description: "You won't really have much trouble getting along! Circumstances will conspire to make you friends, and they will like you well enough. They'll definitely be fun just to hang around with, though if you want them to become something even more, you'll have to put in the extra work." },
    { id: 'best_friends', title: 'BEST FRIENDS', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/r3.png', cost: 10, description: "They will totally get along with you like two peas in a pod shortly after your first meeting, and the two of you will become fast friends, making lots of happy memories together. They'll be one of your closest friends, or maybe you'll become even closer." },
    { id: 'lovey_dovey', title: 'LOVEY DOVEY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/r4.png', cost: 15, description: "You don't even have to try to earn their affection; they will absolutely adore you pretty much the moment that you meet! This can remain a platonic affection, or you can decide for it to progress into a romantic love. Either way, it's going to be nice having your own cheerleader." },
    { id: 'subservient', title: 'SUBSERVIENT', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/r5.png', cost: 0, description: "It doesn't really matter what they feel about you! After all, since you created them with your own magic, you can pretty much have them act however you please. Afford them some autonomy if you wish, or micromanage their every move completely.", requirement: 'Requires, and is required if, not Mage' },
];

export const COMPANION_PERSONALITY_TRAITS: CompanionOption[] = [
    { id: 'shy', title: 'SHY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p1.png', cost: 0, description: '' },
    { id: 'confident', title: 'CONFIDENT', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p2.png', cost: 2, description: '' },
    { id: 'anxious', title: 'ANXIOUS', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p3.png', cost: 0, description: '' },
    { id: 'brave', title: 'BRAVE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p4.png', cost: 2, description: '' },
    { id: 'reserved', title: 'RESERVED', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p5.png', cost: 0, description: '' },
    { id: 'playful', title: 'PLAYFUL', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p6.png', cost: 2, description: '' },
    { id: 'grumpy', title: 'GRUMPY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p7.png', cost: 0, description: '' },
    { id: 'laid_back', title: 'LAID BACK', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p8.png', cost: 2, description: '' },
    { id: 'selfish', title: 'SELFISH', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p9.png', cost: 0, description: '' },
    { id: 'kind', title: 'KIND', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p10.png', cost: 2, description: '' },
    { id: 'ditzy', title: 'DITZY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p11.png', cost: 0, description: '' },
    { id: 'bright', title: 'BRIGHT', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p12.png', cost: 2, description: '' },
    { id: 'sad', title: 'SAD', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p13.png', cost: 0, description: '' },
    { id: 'cheerful', title: 'CHEERFUL', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p14.png', cost: 2, description: '' },
    { id: 'sleepy', title: 'SLEEPY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p15.png', cost: 0, description: '' },
    { id: 'energetic', title: 'ENERGETIC', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p16.png', cost: 2, description: '' },
    { id: 'awkward', title: 'AWKWARD', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p17.png', cost: 0, description: '' },
    { id: 'charismatic', title: 'CHARISMATIC', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p18.png', cost: 2, description: '' },
    { id: 'prudish', title: 'PRUDISH', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p19.png', cost: 0, description: '' },
    { id: 'flirty', title: 'FLIRTY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p20.png', cost: 2, description: '' },
    { id: 'simple', title: 'SIMPLE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p21.png', cost: 0, description: '' },
    { id: 'creative', title: 'CREATIVE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p22.png', cost: 2, description: '' },
    { id: 'smug', title: 'SMUG', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p23.png', cost: 0, description: '' },
    { id: 'humble', title: 'HUMBLE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p24.png', cost: 2, description: '' },
    { id: 'prissy', title: 'PRISSY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p25.png', cost: 0, description: '' },
    { id: 'pragmatic', title: 'PRAGMATIC', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p26.png', cost: 2, description: '' },
    { id: 'brash', title: 'BRASH', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p27.png', cost: 0, description: '' },
    { id: 'wise', title: 'WISE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p28.png', cost: 2, description: '' },
    { id: 'lazy', title: 'LAZY', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p29.png', cost: 0, description: '' },
    { id: 'determined', title: 'DETERMINED', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/p30.png', cost: 2, description: '' },
];

export const COMPANION_PERKS: CompanionOption[] = [
    { id: 'inhuman_form', title: 'INHUMAN FORM', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pe1.png', cost: 5, description: "Things like, say, a girl with cat ears is completely fine, but if you want to complete something completely inhuman like a centaur or lamia, you're going to have to pick this choice. Create their monstrous form with 40 Beast Points on the Reference Page excluding options marked with an *." },
    { id: 'special_weapon', title: 'SPECIAL WEAPON', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pe2.png', cost: 5, description: "They will either already possess or be granted a unique enchanted weapon that can be created using 20 Weapons Points down below, or they can just copy yours. This will allow them to channel their abilities more efficiently, allowing them take two extra Kaarn-level spells, or one extra Purth-level spell." },
    { id: 'signature_power', title: 'SIGNATURE POWER', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pe3.png', cost: 5, description: "Your companion will have a signature power which she's most known for, to be affected by one of the boosts on this list: pastebin.com/GkqPm98A. Can be taken multiple times, but each purchase beyond the first will cost 10 Points. If you choose a Xuth-tier spell, the price of this perk is doubled." },
    { id: 'impressive_career', title: 'IMPRESSIVE CAREER', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pe4.png', cost: 5, description: "Choose one of the organizations listed on Page 6 or any applicable groups elsewhere in the CYOA. Your companion is now part of that group and gets associated benefits, and can help you join. Double price for Holy Knights or IDPA, triple price for Red-Jade Council. Can't join political careers.", requirement: 'Must be Human' },
    { id: 'dark_magician', title: 'DARK MAGICIAN', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pe5.png', cost: 3, description: "This companion dabbles in the black arts, which can provide them some incredible but terrible powers. Every time you take this perk, the companion can have one Sinthru-level spell, as long as it's within a blessing where they already have at least two spells of any level. Can be taken up to 4 times." },
];

export const COMPANION_POWER_LEVELS: CompanionOption[] = [
    { id: 'below_average', title: 'BELOW AVERAGE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pl1.png', cost: 0, description: "They are definitely among the least powerful mages in the world. Sure, they're still leagues above mundanes, but they're probably going to work best as support rather than direct fighters.\n\nThey can be given the Essential Boons, one Purth-level spell, and three Kaarn-level spells, spread across a maximum of two Blessings." },
    { id: 'average', title: 'AVERAGE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pl2.png', cost: 15, description: "This is the level of magical acumen most majority of mages are at. Good enough to learn spells in a couple different blessings, making them very formidable fighters.\n\nThey can be given the Essential Boons, two Purth-level spells, and six Kaarn-level spells, spread across a maximum of three Blessings." },
    { id: 'above_average', title: 'ABOVE AVERAGE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Ref/pl3.png', cost: 30, description: "They're a particularly talented mage that stands head-and-shoulders above their peers.\n\nThey can be given the Essential Boons, one Xuth-level spell (if they have at least four spells within the same blessing), two Purth-level spells, and six Kaarn-level spells, spread across a maximum of four Blessings. Can't have Maria's Gift." },
];

// WEAPONS
export const WEAPON_INTRO = {
    imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/intro.png',
    description: "You will have to decide how, exactly, each carved Blessing is used by your weapon. For projectile spells, it's as simple as launching them from the tip: but for other spells, you may have to get creative!"
};

export const WEAPON_CATEGORIES: CompanionOption[] = [
    { id: 'blunt_melee', title: 'BLUNT MELEE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat1.png', description: "Pretty tough sturdy weapons good for whacking other mages around. They can't use ranged attacks, but can release a different spell effect with every hit in order to massively augment your blows. A good hammer with a good spell can send other mages flying! This category also includes gauntlets.", requirement: 'Can only choose one category' },
    { id: 'bladed_melee', title: 'BLADED MELEE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat2.png', description: "Blades are good against mundanes, but most fights between mages tend to be PG-rated. While it's possible to give mages a lot of bump and bruises, it's pretty damn hard to lop a limb off or disembowel them or anything gorey like that. Ranged spells can be 'fired' from the end of the blade.", requirement: 'Can only choose one category' },
    { id: 'grenades', title: 'GRENADES', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat3.png', description: "See the description for Launchers. These are not quite as powerful, nor can they be fired as far, but they're much more numerous and quick; just keep a grenade belt on you and start lobbing them as fast as you can, filling the entire battlefield with a dozen different spell effects.", requirement: 'Can only choose one category' },
    { id: 'wand', title: 'WAND', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat4.png', description: "The default weapon, and the one I'd recommend for any mages confused as to how the other weapons would work with certain spells. Wands act as an extension of your will, and firing off spells with them is as easy as doing so with your own hands. Plus, you can give them cute customizations!", requirement: 'Can only choose one category' },
    { id: 'staff', title: 'STAFF', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat5.png', description: "A bit more 'serious' than the wand. Staffs are generally more powerful, augmenting the spells emblazoned upon them, yet they're much slower and more unwieldy to use. They're better used for those big, climatic attacks rather than a bunch of small, regular ones.", requirement: 'Can only choose one category' },
    { id: 'bow', title: 'BOW', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat6.png', description: "Probably the cutest of the conventional weapons. Similar to the gun, this unleashes spell effects on direct targets, but its piercing power makes them even more devastating, often causing spells to explode out from inside of their target. Requires a ton of skill and training, though!", requirement: 'Can only choose one category' },
    { id: 'gun', title: 'GUN', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat7.png', description: "As a rule of thumb, the faster it fires, the less effect each shot has. Therefore, each bullet fired usually represents a fraction of the power of a full spell, but with enough lead pouring downstream, it quickly adds up. Bullets are 'charged' with spells and release their effects on the targets they hit.", requirement: 'Can only choose one category' },
    { id: 'launcher', title: 'LAUNCHER', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/cat8.png', description: "Similar to grenades, but instead of only affecting targets hit directly, the spell's effect is released on the entire surrounding area. For example, use Sonic Boom for a conventional explosion, or Pyromaniac for a fire bomb! Missiles are slower, though, each one needing to be loaded by hand.", requirement: 'Can only choose one category' },
];

export const WEAPON_PERKS: CompanionOption[] = [
    { id: 'chatterbox', title: 'CHATTERBOX', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk1.png', cost: 2, description: "Your weapon is able to talk! Can buy Personality Traits from the Companions section using Weapons Points. Not only can it give you useful advice, but it can perform many other tasks. Ever wanted an AR-15 that also played Bach? No? Oh..." },
    { id: 'transforming', title: 'TRANSFORMING', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk2.png', cost: 5, description: "Choose another Category. Your weapon can now transform between it and its default category, although the transition will take two or three seconds. Greatly boosts your versatility. Can be taken multiple times." },
    { id: 'comically_oversized', title: 'COMICALLY OVERSIZED', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk3.png', cost: 5, description: "Pretty simply, this just makes your weapon really, absurdly big, and boosts its power proportionally. This stacks with High Power for devastating effects. Don't worry, you'll be strong enough to wield the thing pretty easily." },
    { id: 'double_trouble', title: 'DOUBLE TROUBLE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk4.png', cost: 10, description: "You've got two arms, right? So why not two guns, or two swords? It may take some extra training to get the hang of dual wielding, but it can effectively double your weapons' effectiveness and versatility.", requirement: "Can't be Bow" },
    { id: 'high_power', title: 'HIGH POWER', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk5.png', cost: 8, description: "Even without magic applied, your weapon is now strong enough to damage even mages. If a Gun, it fires High-Explosive Incendiary Armor-Piercing (HEIAP) ammunition; if a Sword, it uses advanced nanowire alloy blades; and so on.", requirement: "Can't be Wand or Staff" },
    { id: 'recall', title: 'RECALL', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk6.png', cost: 2, description: "Mages tend to have an extremely firm grip on their weapons, but it's not perfect. If your weapon gets knocked or pulled out of your hand somehow, all you have to do is gesture out to it, and it will do its best to try and fly back into your grip." },
    { id: 'purifying_blade', title: 'PURIFYING BLADE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk7.png', cost: 12, description: "Your weapon has been personally blessed by the Mother and passively stabilizes the universe. This massively boosts the damage it does against Sinthru and Allmillor; such entities seem to fear it. Doesn't help against other mages.", requirement: "Requires Melee Weapon" },
    { id: 'attuned_spell', title: 'ATTUNED SPELL', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk8.png', cost: 15, description: "Your weapon is custom-built to accommodate some of your spells and push them to the absolute max of their power. Choose a spell to get a boost from the list pastebin.com/GkqPm98A. This can be taken multiple times.", requirement: "Requires Weapon" },
    { id: 'thermal_supercharge', title: 'THERMAL SUPERCHARGE', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk9.png', cost: 0, description: "Can be either made of raw ice if you have Ice Cold, or raw flames if you have Pyromaniac. They scale up depending on your tier to be much more damaging than a normal attack would be, and cannot be destroyed as long as you hold them.", requirement: "Requires, and is required if, Thermal Weaponry" },
    { id: 'physically_attached', title: 'PHYSICALLY ATTACHED', imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Weapons/perk10.png', cost: 0, description: "Your weapon is built around your arm, essentially replacing it while it's equipped. This means that you don't have to worry about being disarmed, even by the most powerful telekinetics. Unless you are literally disarmed, of course...", requirement: "Requires, and is required if, Heavily Armed" },
];

// BEASTS
export const BEAST_INTRO = {
    imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/intro.png',
    description: "Mages pretty much love pets. This is an almost universal fact. And what better pet than a powerful, mythological creature? You can decide exactly what they look and act like."
};

export const BEAST_CATEGORIES: CompanionOption[] = [
    { id: 'humanoid', title: 'HUMANOID', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat1.png', description: "Broadly applies to anything bipedal or at least vaguely hominid-esque in stature. You can make creatures that look very human, but never exactly so. It will always be immediately obvious to everyone who sees them, in some way or another, that your beast is not truly part of mankind." },
    { id: 'pawed', title: 'PAWED', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat2.png', description: "This covers pretty much all mammals that have paws, like cats, dogs, otters, and what have you. Compared to ungulates, they tend to be pretty lean and are very fluffy. Great for hugs! These are the most popular type of beast, as they make for excellent pets and companions." },
    { id: 'ungulate', title: 'UNGULATE', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat3.png', description: "This covers all the mammals that have hooves, from horses, to elephants, to rhinoceroses, and all that. Compared to pawed mammals, they tend to be pretty thickset and sturdy and have shorter fur. Great as work animals! They are most popular as mounts. Mages particularly love unicorns." },
    { id: 'avian', title: 'AVIAN', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat4.png', description: "Pretty popular as they're associated with flying. Of course, not all avians are actually capable of flight. Just ask the humble penguin. Signified by their feathers and pokey beaks. They're fairly popular as pets and familiars, but not as much as mammals are." },
    { id: 'reptilian', title: 'REPTILIAN', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat5.png', description: "Not too popular among most, since their scaley bodies and angular features tend to make them unappealing as pets. But some find them absolutely adorable in their own way, and some mages covet them for their association with strength and power." },
    { id: 'aquatic', title: 'AQUATIC', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat6.png', description: "These sorts of pets aren't very popular in most places, but their immense popularity in the Unterseeisch tends to make up for that. They can survive on land just fine, too. In fact, this category also covers amphibians." },
    { id: 'insectoid', title: 'INSECTOID', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat7.png', description: "Probably the least popular pets and familiars, especially if we're talking anything besides butterflies and the occasional moth. They just creep most people out! But they're good for mages who like scaring and intimidating others, and again, some find them weirdly cute." },
    { id: 'abstract', title: 'ABSTRACT', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/cat8.png', description: "This encompasses perhaps the broadest range of creatures, since they are no longer required to even look remotely like a real animal. They can be formed in ways that defy all biological sense, and are utterly unique to the mage who owns them." },
];

export const BEAST_SIZES: CompanionOption[] = [
    { id: 'tiny', title: 'TINY', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/size1.png', description: "Commonly associated with fairy-esque beasts. They're known for often possessing great magical prowess, but are physically frail and can hardly muster enough strength to lift a milk jug. At most, they're around the size of a housecat." },
    { id: 'small', title: 'SMALL', cost: 10, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/size2.png', description: "Big enough to wrap your arms around and give a big hug! At this size, they can be very effective physically against mundane targets, although they will still struggle when fighting against mages. At most, they're around the size of a large wolf." },
    { id: 'medium', title: 'MEDIUM', cost: 25, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/size3.png', description: "Now we're getting somewhere! At this point, they are about the size of an adult human or bigger. With the right perks, they can be a threat even to mages, or at least a distraction. At most, they're around the size of a large horse." },
    { id: 'large', title: 'LARGE', cost: 35, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/size4.png', description: "By this point, their durability and physical damage output is increasing exponentially alongside their size. Hell, with their weight, they might be able to just squish a mage! At most, they're much larger than an elephant." },
    { id: 'humongous', title: 'HUMONGOUS', cost: 50, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/size5.png', description: "This is truly a legendary beast, towering over their foes and capable of dominating an entire battlefield! Mundane warriors cringe in horror, and even other mages will be intimidated. At most, they're around the size of a multi story building." },
];

export const BEAST_PERKS: CompanionOption[] = [
    { id: 'chatterbox_beast', title: 'CHATTERBOX *', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk1.png', description: "Your beast has human-like sapience and can speak. You can purchase Personality Traits for it from the list below, using Beast Points." },
    { id: 'noble_steed', title: 'NOBLE STEED', cost: 3, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk2.png', description: "It's always possible to ride most beasts in a pinch, but this Upgrade makes them faster and naturally suited to accepting riders comfortably for very long durations, making for perfect mounts. Naturally, they must be at least Medium size or larger.", requirement: "Requires Medium size or larger" },
    { id: 'free_flying', title: 'FREE FLYING', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk3.png', description: "Your beast will be given a pair of wings big enough to propel them through the air! Tiny beasts can reach 300 MPH; Medium beasts can reach 200 MPH; and Humongous beasts can reach 100 MPH. Acceleration also decreases with size." },
    { id: 'hybrid', title: 'HYBRID', cost: 4, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk4.png', description: "The categories above a bit too limiting for you? Choose a second Category. You can mix and match traits between the two categories however you see fit. Some truly bizarre creatures have been created this way! Can be taken multiple times." },
    { id: 'elemental_breath', title: 'ELEMENTAL BREATH', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk5.png', description: "The beast can now expel some sort of damaging substance from its mouth. Good ol fire? An ancient of water? Acid? Poison? Something else? The choice is all yours! The amount produced obviously varies depending on the beast's size." },
    { id: 'natural_weaponry', title: 'NATURAL WEAPONRY', cost: 2, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk6.png', description: "This varies massively depending on the sort of beast we're dealing with. Maybe they're a wolf with preternaturally sharp claws? Or a serpent with powerfully constricting coils? Whatever the case, they can do slight damage to mages." },
    { id: 'weakening_poison', title: 'WEAKENING POISON', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk7.png', description: "Your beast is venomous or can spit a poison that relaxes the muscles of even a mage, sapping them slowly of their energy. Given enough toxin, they can eventually be paralyzed completely! Quite coveted by alchemists." },
    { id: 'unnerving_appearance', title: 'UNNERVING APPEARANCE', cost: 3, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk8.png', description: "Your beast has a truly disturbing, eldritch appearance, to the point you horrify or shake the sanity of weak-willed or sensitive. It's not too bad once you get used to it, though. Kinda cute, in a way.", requirement: "Free if Undead" },
    { id: 'steel_skin', title: 'STEEL SKIN', cost: 6, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk9.png', description: "Your beast's skin is somehow hardened and quite difficult for even mages to do much damage to. Maybe they're covered in scales as solid as metal, or a complex chitinous or fibrous armor, or maybe their flesh is merely preternaturally durable.", requirement: "Free if Automaton" },
    { id: 'slime', title: 'SLIME', cost: 4, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk10.png', description: "Your beast is partially made out of a slime which is, by default, quite bouncing, sloshy and solid, like a water balloon mixed with a pillow. In combat, though, they can become sticky, slowing or even slowly acidically dissolving foes." },
    { id: 'elemental', title: 'ELEMENTAL', cost: 6, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk11.png', description: "The beast will appear to be covered in or made out of fire, water, ice, lightning, a poisonous slime, or any other similar material. This will not boost their durability, but can harm enemies who draw too near or attack physically." },
    { id: 'chlorophyll', title: 'CHLOROPHYLL', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk12.png', description: "The beast will appear to be made out of either plant like or fungal material, and will be massively rejuvenated by direct sunlight, energizing and healing it. It's not more vulnerable to fire per se, but burns do disable this healing in a localized areas." },
    { id: 'magical_beast', title: 'MAGICAL BEAST *', cost: 15, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk13.png', description: "Can be purchased multiple times. Beast can use one spell from pg 3-5 which: 1. Cannot be from Blessings of Good Tidings, Bitter Dissatisfaction, Defeat, or Love. 2. Cannot have any requirements. 3. Cannot be Kaarn-level spells." },
    { id: 'automaton_perk', title: 'AUTOMATON', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk14.png', description: "Your beast is not a genuine biological creature, but an artificial facsimile! They tend to be quite intelligent and have extremely tough metallic alloys instead of skin. If destroyed, they can self destruct into a massive explosion.", requirement: "Requires, and is required if, Robotocist or Nanite Form" },
    { id: 'undead_perk', title: 'UNDEAD', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Beasts/perk15.png', description: "They don't smell nice, and they're not exactly pretty, either. On the other hand, they have no biological needs, are extremely resilient to pain or damage, and will slowly pull themselves back together if torn to pieces.", requirement: "Requires, and is required if, Undead Beast" },
];

// VEHICLES
export const VEHICLE_INTRO = {
    imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/intro.png',
    description: "Mages can already fly around quickly, but vehicles tend to be much easier and have much faster acceleration, so they're good for leisure and combat situations. They look cool, too."
};

export const VEHICLE_CATEGORIES: CompanionOption[] = [
    { id: 'motorcycle', title: 'MOTORCYCLE', cost: 0, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat1.png', description: "A really fun, simple vehicle. Just try not to crash! Mages tend to get launched like a catapult, going flying through brick walls and everything! By default, its fastest possible speed is 200 mph.", requirement: "Can only choose one category" },
    { id: 'car', title: 'CAR', cost: 10, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat2.png', description: "Ever longed to find yourself behind the wheel of a large automobile? Your car will have all the best and latest upgrades, and can be of any model. By default, its fastest possible speed is 300 mph.", requirement: "Can only choose one category" },
    { id: 'submarine', title: 'SUBMARINE', cost: 10, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat3.png', description: "There's a lot to be found under the sea, from entire thriving cities to ancient ruins full of wonders. Hell, there's a whole Dominion down there! By default, its fastest possible speed is 300 mph.", requirement: "Can only choose one category" },
    { id: 'boat', title: 'BOAT', cost: 10, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat4.png', description: "Lorem ipsum. By default, its fastest possible speed is 300 mph.", requirement: "Can only choose one category" },
    { id: 'tank', title: 'TANK', cost: 20, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat5.png', description: "While quite slow, and not as offensively powerful as mechas, it is more sturdy and well-armored, making it optimal for defensive positions. By default, its fastest possible speed is 100 mph.", requirement: "Can only choose one category" },
    { id: 'plane', title: 'PLANE', cost: 30, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat6.png', description: "Good for travelling across vast distances quite quickly, but it lacks the precise movement of helicopters or the destructive power of mechas. By default, its fastest possible speed is 500 mph.", requirement: "Can only choose one category" },
    { id: 'helicopter', title: 'HELICOPTER', cost: 30, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat7.png', description: "Can be kind of hard to drive, but allows easy movement in all directions to rain death on your enemies from above. By default, its fastest possible speed is 300 mph.", requirement: "Can only choose one category" },
    { id: 'mecha', title: 'MECHA', cost: 40, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/cat8.png', description: "These terrifyingly massive humanoid robots are considered some of the most fearsome weapons on earth, able to compete with mages! By default, its fastest possible speed is 400 mph.", requirement: "Can only choose one category" },
];

export const VEHICLE_PERKS: CompanionOption[] = [
    { id: 'chatterbox_vehicle', title: 'CHATTERBOX', cost: 3, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk1.png', description: "Be it magically given a soul, or a typical AI, your vehicle has a mind of its own! It can drive itself, perform all sorts of tasks and commands, and even talk to you. Can buy Personality Traits from the Companions section using Vehicle Points.", requirement: "Free for Car" },
    { id: 'comically_oversized_vehicle', title: 'COMICALLY OVERSIZED', cost: 10, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk2.png', description: "Bigger really is better! Make that car big enough to live in comfortably, or turn that boat into a yacht or a pirate ship, or that mecha into a proper 10-story tall gundam! These larger vehicles are more durable and powerful than the defaults." },
    { id: 'transforming_vehicle', title: 'TRANSFORMING', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk3.png', description: "Choose a second category; now your vehicle can transform between the two at the push of a button! Can be purchased multiple times. You don't have to purchase the other category, but it can't be more expensive than the default." },
    { id: 'hellfire_volley', title: 'HELLFIRE VOLLEY', cost: 8, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk4.png', description: "Fires volleys of small but quick heat-seeking missiles that devastate other vehicles and even do moderate damage to any mages who are caught directly in the cluster explosion. Pretty effective, but it's possible for the missiles to be outran.", requirement: "Free for Tank and Mecha" },
    { id: 'speed_boost', title: 'SPEED BOOST', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk5.png', description: "There's plenty of ways to make things go faster, from complex magical enchantments, to simply strapping rockets to it. In any case, this increases the vehicle's maximum speed by 100 MPH. This can be purchased up to 3 times." },
    { id: 'force_field', title: 'FORCE FIELD', cost: 7, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk6.png', description: "For when armor won't cut it, it's best to avoid taking any hits in the first place. This gear consumes a lot of energy soaking up damage on the vehicle's behalf, but if subjected to too powerful an assault, it will need to shut down to recharge." },
    { id: 'nanowire_armor', title: 'NANOWIRE ARMOR', cost: 7, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk7.png', description: "Composed of germanium wires each billionths of a meter in diameter and reinforced with directed energy reactive armour, allowing the vehicle to tank immense amounts of damage without so much as a chip on the paint." },
    { id: '"houdini"_system', title: '"HOUDINI" SYSTEM', cost: 5, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk8.png', description: "An advanced cloaking system that hides your vehicle almost completely from the visible spectrum, leaving only a faint blur, although it can still be detected via other means like infrared. It makes no sounds while cloaked, but can't fire its weapons." },
    { id: 'the_trident', title: 'THE TRIDENT', cost: 9, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk9.png', description: "An ordinary gun does little to a mage... but this no ordinary gun. It's actually an automatic railgun firing shells at mach 7, over thrice as fast as regular bullets! Legend says it costs 400,000$ to fire this baby for only 12 seconds." },
    { id: 'armageddon_cannon', title: 'ARMAGEDDON CANNON', cost: 15, imageSrc: 'https://saviapple.neocities.org/Seinaru_Magecraft_Girls/img/Vehicles/perk10.png', description: "Fires a magitech missile that bursts in midair, creating a point of immense density that draws in objects with its powerful gravity well, before triggering an antimatter explosion powerful enough to seriously wound even a mage!", requirement: "Requires Tank or Mecha" },
];